# ISARIC REDCap database analysis: varnames
# Variable names as cocatenated quoted vector
# Centre for Medical Informatics, Usher Institute, University of Edinburgh 2020

c("subjid", "redcap_event_name", "redcap_repeat_instrument", "redcap_repeat_instance", "redcap_data_access_group", 
"participant_identification_number_pin_complete", "tiers_faorres___1", "tiers_faorres___2", "tiers_faorres___3", 
"tiers_consent_complete", "dsstdat", "sitename", "corona_ieorres", "coriona_ieorres2", "fever", "cough", "dyspnoe", 
"ari", "symptoms_epi_travel", "symptoms_epi_physical", "symptoms_epi_healthfac", "symptoms_epi_lab", "symptoms_epi_pathogen", 
"symptoms_epi_animal", "inclusion_criteria_complete", "sex", "agedatyn", "agedat", "age_estimateyears", "age_estimateyearsu", 
"ethnic___1", "ethnic___2", "ethnic___3", "ethnic___4", "ethnic___5", "ethnic___6", "ethnic___7", "ethnic___8", "ethnic___9",
"ethnic___10", "healthwork_erterm", "labwork_erterm", "pregyn_rptestcd", "other_ethnic", "egestage_rptestcd", "postpart_rptestcd", 
"pregout_rptestcd", "dlvrdtc_rptestcd", "aplb_lbperf", "aplb_lborres", "aplb_lbmethod", "aplb_lbmethodoth", "
apdm_age", "apvs_weight", "apvs_weightu", "apsc_gestout", "estgest", "apsc_brfedind", "apsc_brfedindy",
"apsc_brdisdat", "apsc_dvageind", "apsc_vcageind", "demographics_complete", "cestdat", "hostdat", "hosttim", 
"hooccur", "siteid_transfer", "hostdat_transfer", "subjidcat_transfer", "subjid_transfer", "travel_erterm", 
"supper_trcntry", "supper_trcity", "erendat", "travel_erterm_2", "supper_trcntry_2", "supper_trcity_2", 
"erendat_2", "animal_eryn", "animal_erterm", "animal_erdat", "animal_eryn_2", "animal_erterm_2", 
"animal_erdat_2", "onset_and_admission_complete", "temp_vsyn", "temp_vsorres", "temp_vsorresu", 
"hr_vsyn", "hr_vsorres", "rr_vsyn", "rr_vsorres", "sysbp_vsyn", "sysbp_vsorres", "diabp_vsyn", 
"admission_diabp_vsorres", "dehydration_vsorres", "stercap_vsyn", "stercap_vsorres", "oxy_vsyn", 
"oxy_vsorresu", "oxy_vsorres", "fever_ceoccur_v2", "cough_ceoccur_v2", "coughsput_ceoccur_v2", 
"coughhb_ceoccur_v2", "sorethroat_ceoccur_v2", "runnynose_ceoccur_v2", "earpain_ceoccur_v2", "wheeze_ceoccur_v2", 
"chestpain_ceoccur_v2", "myalgia_ceoccur_v2", "jointpain_ceoccur_v2", "fatigue_ceoccur_v2", "shortbreath_ceoccur_v2",
"lowerchest_ceoccur_v2", "headache_ceoccur_v2", "confusion_ceoccur_v2", "seizures_cecoccur_v2", "abdopain_ceoccur_v2", 
"vomit_ceoccur_v2", "diarrhoea_ceoccur_v2", "conjunct_ceoccur_v2", "rash_ceoccur_v2", "skinulcers_ceoccur_v2",
"lymp_ceoccur_v2", "bleed_ceoccur_v2", "bleed_ceterm_v2", "bleed_cetermy_v2", "admission_signs_and_symptoms_complete",
"chrincard", "chronicpul_mhyn", "asthma_mhyn", "renal_mhyn", "modliv", "mildliver", "chronicneu_mhyn", 
"malignantneo_mhyn", "chronichaemo_mhyn", "aidshiv_mhyn", "obesity_mhyn", "diabetescom_mhyn", "diabetes_mhyn", 
"rheumatologic_mhyn", "dementia_mhyn", "malnutrition_mhyn", "smoking_mhyn", "other_mhyn", "otherrisktext", 
"comorbidities_complete", "immno_cmtrt", "infect_cmtrt", "infect", "preadmission_treatment_complete", 
"cmtrt", "cmdose", "cmdosfrq", "cmdosfrqoth", "cmroute", "cmrouteoth", "preadmission_medication_complete", 
"daily_dsstdat", "daily_hoterm", "daily_fi02_lbyn", "daily_fio2_lborres", "daily_sa02_lbyn", "daily_sao2_lborres",
"daily_pao2_lbyn", "daily_pao2_lborres", "daily_pao2_lborresu", "daily_pao2_lbspec", "daily_pco2_lbyn", 
"daily_pco2_lborres", "daily_pco2_lborresu", "daily_ph_lbyn", "daily_ph_lborres", "daily_hco3_lbyn", 
"daily_hco3_lborres", "daily_baseex_lbyn", "daily_baseex_lborres", "avpu_vsorres", "daily_gcs_lbyn",
"daily_gcs_vsorres", "systolic_vsyn", "systolic_vsorres", "diastolic_vsyn", "diastolic_vsorres", "daily_meanart_lbyn",
"daily_meanart_vsorres", "daily_urine_lbyn", "daily_urine_lborres", "daily_noninvasive_prtrt", "daily_invasive_prtrt",
"daily_nasaloxy_cmtrt", "daily_ecmo_prtrt", "daily_rrt_cmtrt", "daily_inotrope_cmyn", "daily_dopless5_cmtrt", 
"daily_dop5to15_cmtrt", "daily_dopgr15_cmtrt", "daily_neuro_cmtrt", "daily_nitritc_cmtrt", "daily_prone_cmtrt", 
"daily_trach_prperf", "daily_prperf", "daily_other_prtrt", "daily_lbperf", "daily_lbdat", "daily_hb_lbyn", 
"daily_hb_lborres", "daily_hb_lborresu", "daily_wbc_lbyn", "daily_wbc_lborres", "daily_wbc_lborresu",
"daily_lymp_lbyn", "daily_lymp_lborres", "daily_neutro_lbyn", "daily_neutro_lborres", "daily_haematocrit_lbyn",
"daily_haematocrit_lborres", "daily_plt_lbyn", "daily_plt_lborres", "daily_plt_lborresu", "daily_aptt_lbyn",
"daily_aptt_lborres", "daily_pt_inr_lbyn", "daily_pt_lborres", "daily_inr_lborres", "daily_alt_lbyn", "daily_alt_lborres", 
"daily_bil_lbyn", "daily_bil_lborres", "daily_bil_lborresu", "daily_ast_lbyn", "daily_ast_lborres", "daily_glucose_lbyn", 
"daily_glucose_lborres", "daily_glucose_lborresu", "daily_bun_lbyn", "daily_bun_lborres", "daily_bun_lborresu",
"daily_lactate_lbyn", "daily_lactate_lborres", "daily_lactate_lborresu", "daily_ldh_lbyn", "daily_ldh_lborres", 
"daily_cpk_lby", "daily_cpk_lbyn_2", "daily_creat_lbyn", "daily_creat_lborres", "daily_creat_lborresu", 
"daily_sodium_lbyn", "daily_sodium_lborres", "daily_potassium_lbyn", "daily_potassium_lborres", 
"daily_procal_lbyn", "daily_procal_lborres", "daily_crp_lbyn", "daily_crp_lborres", "xray_prperf", 
"infiltrates_faorres", "daily_form_complete", "mbperf", "influ_mbyn", "influ_mbcat", "influother_mborres", 
"corna_mbcat", "corna_mbcaty", "coronaother_mborres", "rsv_mbcat", "adeno_mbcat", "bact_mborres", "bacteria_mborres", 
"other_mbyn", "other_mborres", "clinicalpneu_mborres", "infectuk_mborres", 
"infectious_respiratory_disease_pathogen_diagnosis_complete", "daily_mbperf", "llimsno_bnum", "mbdat", "mbspec",
"other_mbspec", "mbmethod", "other_mbmethod", "mborres", "mbtestcd", "infectious_respiratory_disease_pathogen_testing_complete",
"antiviral_cmyn", "antiviral_cmtrt___1", "antiviral_cmtrt___2", "antiviral_cmtrt___3", "antiviral_cmtrt___4", "antiviral_cmtrt___5",
"antiviral_cmtrt___6", "neuro_cmtrt", "othantiviral_cmtrt", "othantiviral2_cmyn", "othhantiviral2_cmtrt", "othantiviral3_cmyn",
"othantiviral3_cmtrt", "othantiviral4_cmyn", "othantiviral4_cmtrt", "othantiviral5_cmyn", "othantiviral5_cmtrt", "antibiotic_cmyn",
"antibiotic_cmtrt", "antibiotic2_cmyn", "antibiotic2_cmtrt", "antibiotic3_cmyn", "antibiotic3_cmtrt", "antibiotic4_cmyn", 
"antibiotic4_cmtrt", "antibiotic5_cmyn", "antibiotic5_cmtrt", "corticost_cmyn", "corticost_cmroute", "corticost_cmtrt",
"corticost_cmdose", "antifung_cmyn", "antifungal_cmtrt", "icu_hoterm", "icu_hostdat", "icu_hoendat", "hodur", 
"oxygen_cmoccur", "noninvasive_proccur", "invasive_proccur", "pronevent_prtrt", "inhalednit_cmtrt", "tracheo_prtrt",
"extracorp_prtrt", "rrt_prtrt", "inotrop_cmtrt", "invasive_prdur", "excorp_prdur", "inotrope_cmdur", "other_cmyn", "other_cm", 
"treatment_complete", "vrialpneu_ceoccur", "bactpneu_ceoccur", "ards_ceoccur", "cryptogenic_ceterm", "pneumothorax_ceterm", 
"pleuraleff_ceterm", "bronchio_ceterm", "meningitis_ceterm", "seizure_ceterm", "stroke_ceterm", "heartfailure_ceterm", 
"endocarditis_aeterm", "arrhythmia_ceterm", "ischaemia_ceterm", "cardiacarrest_ceterm", "bacteraemia_ceterm",
"coagulo_ceterm", "aneamia_ceterm", "rhabdomyolsis_ceterm", "renalinjury_ceterm", "gastro_ceterm", "pancreat_ceterm", 
"liverdysfunction_ceterm", "hyperglycemia_aeterm", "hypoglycemia_ceterm", "other_ceoccur", "other_ceterm", 
"complications_complete", "recruitment", "study_1_name", "study_1_id", "study_2", "study_2_name", "study_2_id", 
"study_3", "study_3_name", "study_3_id", "study_participation_complete", "dsterm", "dsstdtcyn", "dsstdtc", 
"suppds_qval", "oxygen_proccur", "renal_proccur", "other_cmoccur", "other_cmtrt", "siteid", "siteyn", "subjidcat", 
"transfer_subjid", "outcome_complete", "core_addinfo", "core_additional_information_complete", "age", 
"onset2admission", "ethnicity", "alt_conscious", "hypoxic_target", "o2_rx", "news", "news1", "news2", 
"onset2admission2", "news3")