# RP edited file from REDCap based EMH prevision changes - overwrite factors with factors. 


#Setting Factors (will NOT create new variables for factors)
# we've removed all  namings
data$redcap_event_name = factor(data$redcap_event_name,levels=c("day_1_hospital_adm_arm_1","day_3_arm_1","day_6_arm_1","day_9_arm_1","additional_days_arm_1","dischargedeath_arm_1","day_1_hospitalicu_arm_2","day_3_arm_2","day_6_arm_2","day_9_arm_2","additional_days_arm_2","dischargedeath_arm_2","day_1_arm_3","day_2_arm_3","day_3_arm_3","day_4_arm_3","day_5_arm_3","day_6_arm_3","day_7_arm_3","day_8_arm_3","day_9_arm_3","day_10_arm_3","day_11_arm_3","day_12_arm_3","day_13_arm_3","day_14_arm_3","additional_days_arm_3","dischargedeath_arm_3"))
data$redcap_repeat_instrument = factor(data$redcap_repeat_instrument,levels=c("preadmission_medication","infectious_respiratory_disease_pathogen_testing","daily_form"))
data$tiers_faorres___1 = factor(data$tiers_faorres___1,levels=c("0","1"))
data$tiers_faorres___2 = factor(data$tiers_faorres___2,levels=c("0","1"))
data$tiers_faorres___3 = factor(data$tiers_faorres___3,levels=c("0","1"))
data$tiers_consent_complete = factor(data$tiers_consent_complete,levels=c("0","1","2"))
data$participant_identification_number_pin_complete = factor(data$participant_identification_number_pin_complete,levels=c("0","1","2"))
data$covid19_new = factor(data$covid19_new,levels=c("1"))
data$corona_ieorres = factor(data$corona_ieorres,levels=c("1","0"))
data$coriona_ieorres2 = factor(data$coriona_ieorres2,levels=c("1","0"))
data$fever = factor(data$fever,levels=c("1","0"))
data$cough = factor(data$cough,levels=c("1","0"))
data$dyspnoe = factor(data$dyspnoe,levels=c("1","0"))
data$ari = factor(data$ari,levels=c("1","0"))
data$symptoms_epi_travel = factor(data$symptoms_epi_travel,levels=c("1","2","3"))
data$symptoms_epi_physical = factor(data$symptoms_epi_physical,levels=c("1","2","3"))
data$symptoms_epi_healthfac = factor(data$symptoms_epi_healthfac,levels=c("1","2","3"))
data$symptoms_epi_lab = factor(data$symptoms_epi_lab,levels=c("1","2","3"))
data$symptoms_epi_pathogen = factor(data$symptoms_epi_pathogen,levels=c("1","2","3"))
data$symptoms_epi_animal = factor(data$symptoms_epi_animal,levels=c("1","2","3"))
data$inclusion_criteria_complete = factor(data$inclusion_criteria_complete,levels=c("0","1","2"))
data$sex = factor(data$sex,levels=c("1","2","3"))
data$agedatyn = factor(data$agedatyn,levels=c("1","0"))
data$age_estimateyearsu = factor(data$age_estimateyearsu,levels=c("1","2"))
data$ethnic___1 = factor(data$ethnic___1,levels=c("0","1"))
data$ethnic___2 = factor(data$ethnic___2,levels=c("0","1"))
data$ethnic___3 = factor(data$ethnic___3,levels=c("0","1"))
data$ethnic___4 = factor(data$ethnic___4,levels=c("0","1"))
data$ethnic___5 = factor(data$ethnic___5,levels=c("0","1"))
data$ethnic___6 = factor(data$ethnic___6,levels=c("0","1"))
data$ethnic___7 = factor(data$ethnic___7,levels=c("0","1"))
data$ethnic___8 = factor(data$ethnic___8,levels=c("0","1"))
data$ethnic___9 = factor(data$ethnic___9,levels=c("0","1"))
data$ethnic___10 = factor(data$ethnic___10,levels=c("0","1"))
data$healthwork_erterm = factor(data$healthwork_erterm,levels=c("1","2","3"))
data$labwork_erterm = factor(data$labwork_erterm,levels=c("1","2","3"))
data$pregyn_rptestcd = factor(data$pregyn_rptestcd,levels=c("1","0","998","999"))
data$postpart_rptestcd = factor(data$postpart_rptestcd,levels=c("1","0","3"))
data$pregout_rptestcd = factor(data$pregout_rptestcd,levels=c("1","2"))
data$aplb_lbperf = factor(data$aplb_lbperf,levels=c("1","2","3"))
data$aplb_lborres = factor(data$aplb_lborres,levels=c("1","2"))
data$aplb_lbmethod = factor(data$aplb_lbmethod,levels=c("1","2"))
data$apdm_age = factor(data$apdm_age,levels=c("1","0"))
data$apvs_weightu = factor(data$apvs_weightu,levels=c("1","2"))
data$apvs_weightnk = factor(data$apvs_weightnk,levels=c("1"))
data$apsc_gestout = factor(data$apsc_gestout,levels=c("1","2","3"))
data$apsc_brfedind = factor(data$apsc_brfedind,levels=c("1","2","3"))
data$apsc_brfedindy = factor(data$apsc_brfedindy,levels=c("1","2","3"))
data$apsc_dvageind = factor(data$apsc_dvageind,levels=c("1","2","3"))
data$apsc_vcageind = factor(data$apsc_vcageind,levels=c("1","2","3","4"))
data$demographics_complete = factor(data$demographics_complete,levels=c("0","1","2"))
data$readm_cov19 = factor(data$readm_cov19,levels=c("1","0","3"))
data$readminreasnk = factor(data$readminreasnk,levels=c("1"))
data$surgefacil = factor(data$surgefacil,levels=c("1","0","3"))
data$hooccur = factor(data$hooccur,levels=c("1","2","3","4"))
data$siteid_transfernk = factor(data$siteid_transfernk,levels=c("1"))
data$hostdat_transfernk = factor(data$hostdat_transfernk,levels=c("1"))
data$subjidcat_transfer = factor(data$subjidcat_transfer,levels=c("1","2","3"))
data$travel_erterm = factor(data$travel_erterm,levels=c("1","2","3"))
data$supper_trcntry = factor(data$supper_trcntry,levels=c("4","5","6","7","8","9","10","11","12","13","14","15","1","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","2","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","3","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","202","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","201","193","194","195","196","197","198","199","200"))
data$travel_erterm_2 = factor(data$travel_erterm_2,levels=c("1","2","3"))
data$supper_trcntry_2 = factor(data$supper_trcntry_2,levels=c("4","5","6","7","8","9","10","11","12","13","14","15","1","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","2","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","3","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","202","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","201","193","194","195","196","197","198","199","200"))
data$animal_eryn = factor(data$animal_eryn,levels=c("1","2","3","4"))
data$animal_eryn_2 = factor(data$animal_eryn_2,levels=c("1","2","3","4"))
data$onset_and_admission_complete = factor(data$onset_and_admission_complete,levels=c("0","1","2"))
data$temp_vsyn = factor(data$temp_vsyn,levels=c("1","0"))
data$temp_vsorresu = factor(data$temp_vsorresu,levels=c("1","2"))
data$hr_vsyn = factor(data$hr_vsyn,levels=c("1","0"))
data$rr_vsyn = factor(data$rr_vsyn,levels=c("1","0"))
data$sysbp_vsyn = factor(data$sysbp_vsyn,levels=c("1","0"))
data$diabp_vsyn = factor(data$diabp_vsyn,levels=c("1","0"))
data$dehydration_vsorres = factor(data$dehydration_vsorres,levels=c("1","2","3"))
data$stercap_vsyn = factor(data$stercap_vsyn,levels=c("1","0"))
data$stercap_vsorres = factor(data$stercap_vsorres,levels=c("1","2","3"))
data$oxy_vsyn = factor(data$oxy_vsyn,levels=c("1","0"))
data$oxy_vsorresu = factor(data$oxy_vsorresu,levels=c("1","2","3"))
data$fever_ceoccur_v2 = factor(data$fever_ceoccur_v2,levels=c("1","2","3"))
data$cough_ceoccur_v2 = factor(data$cough_ceoccur_v2,levels=c("1","2","3"))
data$coughsput_ceoccur_v2 = factor(data$coughsput_ceoccur_v2,levels=c("1","2","3"))
data$coughhb_ceoccur_v2 = factor(data$coughhb_ceoccur_v2,levels=c("1","2","3"))
data$sorethroat_ceoccur_v2 = factor(data$sorethroat_ceoccur_v2,levels=c("1","2","3"))
data$runnynose_ceoccur_v2 = factor(data$runnynose_ceoccur_v2,levels=c("1","2","3"))
data$earpain_ceoccur_v2 = factor(data$earpain_ceoccur_v2,levels=c("1","2","3"))
data$wheeze_ceoccur_v2 = factor(data$wheeze_ceoccur_v2,levels=c("1","2","3"))
data$chestpain_ceoccur_v2 = factor(data$chestpain_ceoccur_v2,levels=c("1","2","3"))
data$myalgia_ceoccur_v2 = factor(data$myalgia_ceoccur_v2,levels=c("1","2","3"))
data$jointpain_ceoccur_v2 = factor(data$jointpain_ceoccur_v2,levels=c("1","2","3"))
data$fatigue_ceoccur_v2 = factor(data$fatigue_ceoccur_v2,levels=c("1","2","3"))
data$shortbreath_ceoccur_v2 = factor(data$shortbreath_ceoccur_v2,levels=c("1","2","3"))
data$ageusia_ceoccur_v2 = factor(data$ageusia_ceoccur_v2,levels=c("1","2","3"))
data$lowerchest_ceoccur_v2 = factor(data$lowerchest_ceoccur_v2,levels=c("1","2","3"))
data$headache_ceoccur_v2 = factor(data$headache_ceoccur_v2,levels=c("1","2","3"))
data$confusion_ceoccur_v2 = factor(data$confusion_ceoccur_v2,levels=c("1","2","3"))
data$seizures_cecoccur_v2 = factor(data$seizures_cecoccur_v2,levels=c("1","2","3"))
data$abdopain_ceoccur_v2 = factor(data$abdopain_ceoccur_v2,levels=c("1","2","3"))
data$vomit_ceoccur_v2 = factor(data$vomit_ceoccur_v2,levels=c("1","2","3"))
data$diarrhoea_ceoccur_v2 = factor(data$diarrhoea_ceoccur_v2,levels=c("1","2","3"))
data$conjunct_ceoccur_v2 = factor(data$conjunct_ceoccur_v2,levels=c("1","2","3"))
data$rash_ceoccur_v2 = factor(data$rash_ceoccur_v2,levels=c("1","2","3"))
data$skinulcers_ceoccur_v2 = factor(data$skinulcers_ceoccur_v2,levels=c("1","2","3"))
data$lymp_ceoccur_v2 = factor(data$lymp_ceoccur_v2,levels=c("1","2","3"))
data$bleed_ceoccur_v2 = factor(data$bleed_ceoccur_v2,levels=c("1","2","3"))
data$bleed_ceterm_v2 = factor(data$bleed_ceterm_v2,levels=c("1","2","3"))
data$anosmia_ceoccur_v2 = factor(data$anosmia_ceoccur_v2,levels=c("1","2","3"))
data$admission_signs_and_symptoms_complete = factor(data$admission_signs_and_symptoms_complete,levels=c("0","1","2"))
data$chrincard = factor(data$chrincard,levels=c("1","2","3"))
data$hypertension_mhyn = factor(data$hypertension_mhyn,levels=c("1","2","3"))
data$chronicpul_mhyn = factor(data$chronicpul_mhyn,levels=c("1","2","3"))
data$asthma_mhyn = factor(data$asthma_mhyn,levels=c("1","0","2"))
data$renal_mhyn = factor(data$renal_mhyn,levels=c("1","2","3"))
data$modliv = factor(data$modliv,levels=c("1","0","2"))
data$mildliver = factor(data$mildliver,levels=c("1","0","2"))
data$chronicneu_mhyn = factor(data$chronicneu_mhyn,levels=c("1","2","3"))
data$malignantneo_mhyn = factor(data$malignantneo_mhyn,levels=c("1","2","3"))
data$chronichaemo_mhyn = factor(data$chronichaemo_mhyn,levels=c("1","2","3"))
data$aidshiv_mhyn = factor(data$aidshiv_mhyn,levels=c("1","2","3"))
data$obesity_mhyn = factor(data$obesity_mhyn,levels=c("1","2","3"))
data$diabetes_type_mhyn = factor(data$diabetes_type_mhyn,levels=c("0","1","2","3"))
data$diabetescom_mhyn = factor(data$diabetescom_mhyn,levels=c("1","2","3"))
data$diabetes_mhyn = factor(data$diabetes_mhyn,levels=c("1","2","3"))
data$rheumatologic_mhyn = factor(data$rheumatologic_mhyn,levels=c("1","2","3"))
data$dementia_mhyn = factor(data$dementia_mhyn,levels=c("1","2","3"))
data$malnutrition_mhyn = factor(data$malnutrition_mhyn,levels=c("1","2","3"))
data$smoking_mhyn = factor(data$smoking_mhyn,levels=c("1","2","3","4"))
data$other_mhyn = factor(data$other_mhyn,levels=c("1","2","3"))
data$vulnerable_transplant = factor(data$vulnerable_transplant,levels=c("1","2","3"))
data$vulnerable_cancers = factor(data$vulnerable_cancers,levels=c("1","2","3"))
data$vulnerable_copd = factor(data$vulnerable_copd,levels=c("1","2","3"))
data$vulnerable_scid = factor(data$vulnerable_scid,levels=c("1","2","3"))
data$vulnerable_immuno = factor(data$vulnerable_immuno,levels=c("1","2","3"))
data$vulnerable_preg = factor(data$vulnerable_preg,levels=c("1","2","3"))
data$comorbidities_complete = factor(data$comorbidities_complete,levels=c("0","1","2"))
data$immno_cmtrt = factor(data$immno_cmtrt,levels=c("1","2","3"))
data$infect_cmtrt = factor(data$infect_cmtrt,levels=c("1","2","3"))
data$chronic_ace_cmoccur = factor(data$chronic_ace_cmoccur,levels=c("1","2","3"))
data$chronic_arb_cmoccur = factor(data$chronic_arb_cmoccur,levels=c("1","2","3"))
data$chronic_nsaid_cmoccur = factor(data$chronic_nsaid_cmoccur,levels=c("1","2","3"))
data$clinical_frailty = factor(data$clinical_frailty,levels=c("1","2","3","4","5","6","7","8","9","10"))
data$preadmission_treatment_complete = factor(data$preadmission_treatment_complete,levels=c("0","1","2"))
data$cmdose_unit = factor(data$cmdose_unit,levels=c("1","2","3","4","5","99"))
data$cmdosfrq = factor(data$cmdosfrq,levels=c("1","2","3","4","5","6","7","8","9","10","11","99"))
data$cmroute = factor(data$cmroute,levels=c("1","2","3","4","5"))
data$preadmission_medication_complete = factor(data$preadmission_medication_complete,levels=c("0","1","2"))
data$daily_hoterm = factor(data$daily_hoterm,levels=c("1","2","3"))
data$daily_temp_vsorresu = factor(data$daily_temp_vsorresu,levels=c("1","2"))
data$daily_temp_vsorresnk = factor(data$daily_temp_vsorresnk,levels=c("1"))
data$daily_fi02_lbyn = factor(data$daily_fi02_lbyn,levels=c("1","2","3"))
data$daily_sa02_lbyn = factor(data$daily_sa02_lbyn,levels=c("1","2","3"))
data$daily_pao2_lbyn = factor(data$daily_pao2_lbyn,levels=c("1","0"))
data$daily_pao2_lborresu = factor(data$daily_pao2_lborresu,levels=c("1","2"))
data$daily_pao2_lbspec = factor(data$daily_pao2_lbspec,levels=c("1","2","3","4"))
data$daily_pco2_lbyn = factor(data$daily_pco2_lbyn,levels=c("1","2"))
data$daily_pco2_lborresu = factor(data$daily_pco2_lborresu,levels=c("1","2"))
data$daily_ph_lbyn = factor(data$daily_ph_lbyn,levels=c("1","0"))
data$daily_hco3_lbyn = factor(data$daily_hco3_lbyn,levels=c("1","0"))
data$daily_baseex_lbyn = factor(data$daily_baseex_lbyn,levels=c("1","0"))
data$avpu_vsorres = factor(data$avpu_vsorres,levels=c("1","2","3","4","5"))
data$daily_gcs_lbyn = factor(data$daily_gcs_lbyn,levels=c("1","0","3"))
data$systolic_vsyn = factor(data$systolic_vsyn,levels=c("1","0"))
data$diastolic_vsyn = factor(data$diastolic_vsyn,levels=c("1","0"))
data$daily_meanart_lbyn = factor(data$daily_meanart_lbyn,levels=c("1","0"))
data$daily_urine_lbyn = factor(data$daily_urine_lbyn,levels=c("1","2","0"))
data$daily_noninvasive_prtrt = factor(data$daily_noninvasive_prtrt,levels=c("1","2","3"))
data$daily_invasive_prtrt = factor(data$daily_invasive_prtrt,levels=c("1","2","3"))
data$daily_nasaloxy_cmtrt = factor(data$daily_nasaloxy_cmtrt,levels=c("1","2","3"))
data$daily_ecmo_prtrt = factor(data$daily_ecmo_prtrt,levels=c("1","2","3"))
data$daily_rrt_cmtrt = factor(data$daily_rrt_cmtrt,levels=c("1","2","3"))
data$daily_inotrope_cmyn = factor(data$daily_inotrope_cmyn,levels=c("1","2","3"))
data$daily_dopless5_cmtrt = factor(data$daily_dopless5_cmtrt,levels=c("1","2","3"))
data$daily_dop5to15_cmtrt = factor(data$daily_dop5to15_cmtrt,levels=c("1","2","3"))
data$daily_dopgr15_cmtrt = factor(data$daily_dopgr15_cmtrt,levels=c("1","2","3"))
data$daily_neuro_cmtrt = factor(data$daily_neuro_cmtrt,levels=c("1","2","3"))
data$daily_nitritc_cmtrt = factor(data$daily_nitritc_cmtrt,levels=c("1","2","3"))
data$daily_prone_cmtrt = factor(data$daily_prone_cmtrt,levels=c("1","2","3"))
data$daily_trach_prperf = factor(data$daily_trach_prperf,levels=c("1","2","3"))
data$daily_prperf = factor(data$daily_prperf,levels=c("1","2","3"))
data$daily_lbperf = factor(data$daily_lbperf,levels=c("1","0"))
data$daily_hb_lbyn = factor(data$daily_hb_lbyn,levels=c("1","0","3"))
data$daily_hbop_lborres = factor(data$daily_hbop_lborres,levels=c("1","2"))
data$daily_hb_lborresu = factor(data$daily_hb_lborresu,levels=c("1","2"))
data$daily_wbc_lbyn = factor(data$daily_wbc_lbyn,levels=c("1","0","3"))
data$daily_wbcop_lborres = factor(data$daily_wbcop_lborres,levels=c("1","2"))
data$daily_wbc_lborresu = factor(data$daily_wbc_lborresu,levels=c("1","2"))
data$daily_lymp_lbyn = factor(data$daily_lymp_lbyn,levels=c("1","0","3"))
data$daily_lympop_lbyn = factor(data$daily_lympop_lbyn,levels=c("1","2"))
data$daily_lymp_lborresu = factor(data$daily_lymp_lborresu,levels=c("1","2","3"))
data$daily_neutro_lbyn = factor(data$daily_neutro_lbyn,levels=c("1","0","3"))
data$daily_neutroop_lbyn = factor(data$daily_neutroop_lbyn,levels=c("1","2"))
data$daily_neutro_lborresu = factor(data$daily_neutro_lborresu,levels=c("1","2","3"))
data$daily_haematocrit_lbyn = factor(data$daily_haematocrit_lbyn,levels=c("1","0"))
data$daily_plt_lbyn = factor(data$daily_plt_lbyn,levels=c("1","0","3"))
data$daily_pltop_lborres = factor(data$daily_pltop_lborres,levels=c("1","2"))
data$daily_plt_lborresu = factor(data$daily_plt_lborresu,levels=c("1","2"))
data$daily_aptt_lbyn = factor(data$daily_aptt_lbyn,levels=c("1","0","3"))
data$daily_apttop_lborres = factor(data$daily_apttop_lborres,levels=c("1","2"))
data$daily_pt_inr_lbyn = factor(data$daily_pt_inr_lbyn,levels=c("1","2","3","4"))
data$daily_ptop_lborres = factor(data$daily_ptop_lborres,levels=c("1","2"))
data$daily_inrop_lborres = factor(data$daily_inrop_lborres,levels=c("1","2"))
data$daily_alt_lbyn = factor(data$daily_alt_lbyn,levels=c("1","0","3"))
data$daily_altop_lbyn = factor(data$daily_altop_lbyn,levels=c("1","2"))
data$daily_bil_lbyn = factor(data$daily_bil_lbyn,levels=c("1","0","3"))
data$daily_bilop_lborres = factor(data$daily_bilop_lborres,levels=c("1","2"))
data$daily_bil_lborresu = factor(data$daily_bil_lborresu,levels=c("1","2"))
data$daily_ast_lbyn = factor(data$daily_ast_lbyn,levels=c("1","0","3"))
data$daily_astop_lborres = factor(data$daily_astop_lborres,levels=c("1","2"))
data$daily_glucose_lbyn = factor(data$daily_glucose_lbyn,levels=c("1","0","3"))
data$daily_glucoseop_lborres = factor(data$daily_glucoseop_lborres,levels=c("1","2"))
data$daily_glucose_lborresu = factor(data$daily_glucose_lborresu,levels=c("1","2"))
data$daily_bun_lbyn = factor(data$daily_bun_lbyn,levels=c("1","0","3"))
data$daily_bunop_lborres = factor(data$daily_bunop_lborres,levels=c("1","2"))
data$daily_bun_lborresu = factor(data$daily_bun_lborresu,levels=c("1","2"))
data$daily_lactate_lbyn = factor(data$daily_lactate_lbyn,levels=c("1","0","3"))
data$daily_lactateop_lbyn = factor(data$daily_lactateop_lbyn,levels=c("1","2"))
data$daily_lactate_lborresu = factor(data$daily_lactate_lborresu,levels=c("1","2"))
data$daily_ldh_lbyn = factor(data$daily_ldh_lbyn,levels=c("1","0","3"))
data$daily_ldhop_lborres = factor(data$daily_ldhop_lborres,levels=c("1","2"))
data$daily_cpk_lby = factor(data$daily_cpk_lby,levels=c("1","0","3"))
data$daily_cpkop_lbyn_2 = factor(data$daily_cpkop_lbyn_2,levels=c("1","2"))
data$daily_creat_lbyn = factor(data$daily_creat_lbyn,levels=c("1","0","3"))
data$daily_creatop_lborres = factor(data$daily_creatop_lborres,levels=c("1","2"))
data$daily_creat_lborresu = factor(data$daily_creat_lborresu,levels=c("1","2","3"))
data$daily_sodium_lbyn = factor(data$daily_sodium_lbyn,levels=c("1","0","3"))
data$daily_sodiumop_lborres = factor(data$daily_sodiumop_lborres,levels=c("1","2"))
data$daily_sodium_lborresu = factor(data$daily_sodium_lborresu,levels=c("1","2"))
data$daily_potassium_lbyn = factor(data$daily_potassium_lbyn,levels=c("1","0","3"))
data$daily_potassiumop_lborres = factor(data$daily_potassiumop_lborres,levels=c("1","2"))
data$daily_potassium_lborresu = factor(data$daily_potassium_lborresu,levels=c("1","2"))
data$daily_procal_lbyn = factor(data$daily_procal_lbyn,levels=c("1","0","3"))
data$daily_procalop_lborres = factor(data$daily_procalop_lborres,levels=c("1","2"))
data$daily_crp_lbyn = factor(data$daily_crp_lbyn,levels=c("1","0","3"))
data$daily_crpop_lborres = factor(data$daily_crpop_lborres,levels=c("1","2"))
data$daily_crp_lborresu = factor(data$daily_crp_lborresu,levels=c("1","2","3"))
data$daily_hba1cop_lborres = factor(data$daily_hba1cop_lborres,levels=c("1","2"))
data$daily_hba1c_lborresnk = factor(data$daily_hba1c_lborresnk,levels=c("1"))
data$xray_prperf = factor(data$xray_prperf,levels=c("1","2","3"))
data$infiltrates_faorres = factor(data$infiltrates_faorres,levels=c("1","2","3"))
data$daily_form_complete = factor(data$daily_form_complete,levels=c("0","1","2"))
data$ni_site = factor(data$ni_site,levels=c("1"))
data$inflammatory_mss = factor(data$inflammatory_mss,levels=c("1","0"))
data$asymptomatic = factor(data$asymptomatic,levels=c("1"))
data$no_symptoms = factor(data$no_symptoms,levels=c("1","2","3"))
data$no_medication = factor(data$no_medication,levels=c("1"))
data$daily_hco3_lborresu = factor(data$daily_hco3_lborresu,levels=c("1","2"))
data$remdesivir = factor(data$remdesivir,levels=c("1","0","2"))
data$remdesivir_last_dose = factor(data$remdesivir_last_dose,levels=c("1","0","2"))
data$daily_haematocrit_lborresu = factor(data$daily_haematocrit_lborresu,levels=c("1","2"))
data$daily_esr_lbyn = factor(data$daily_esr_lbyn,levels=c("1","0","3"))
data$daily_esrop_lbyn = factor(data$daily_esrop_lbyn,levels=c("1","2"))
data$daily_ferr_lbyn = factor(data$daily_ferr_lbyn,levels=c("1","0","3"))
data$daily_ferrop_lbyn = factor(data$daily_ferrop_lbyn,levels=c("1","2"))
data$daily_ferr_lborresu = factor(data$daily_ferr_lborresu,levels=c("1","2"))
data$daily_egfr_lbyn = factor(data$daily_egfr_lbyn,levels=c("1","0","3"))
data$daily_egfrop_lborres = factor(data$daily_egfrop_lborres,levels=c("1","2"))
data$daily_egfr_equation___1 = factor(data$daily_egfr_equation___1,levels=c("0","1"))
data$daily_egfr_equation___2 = factor(data$daily_egfr_equation___2,levels=c("0","1"))
data$daily_egfr_equation___3 = factor(data$daily_egfr_equation___3,levels=c("0","1"))
data$daily_hba1c_lborresu = factor(data$daily_hba1c_lborresu,levels=c("1","2"))
data$mbperf = factor(data$mbperf,levels=c("1","2","3"))
data$influ_mbyn = factor(data$influ_mbyn,levels=c("2","1","0"))
data$influ_mbcat = factor(data$influ_mbcat,levels=c("1","2","3","4","5","7","6","888"))
data$corna_mbcat = factor(data$corna_mbcat,levels=c("2","1","0"))
data$corna_mbcaty = factor(data$corna_mbcaty,levels=c("1","2","3","888"))
data$rsv_mbcat = factor(data$rsv_mbcat,levels=c("2","1","0"))
data$adeno_mbcat = factor(data$adeno_mbcat,levels=c("2","1","0"))
data$bact_mborres = factor(data$bact_mborres,levels=c("1","2"))
data$other_mbyn = factor(data$other_mbyn,levels=c("2","1","0"))
data$clinicalpneu_mborres = factor(data$clinicalpneu_mborres,levels=c("1","0","2"))
data$infectuk_mborres = factor(data$infectuk_mborres,levels=c("1","2"))
data$infectious_respiratory_disease_pathogen_diagnosis_complete = factor(data$infectious_respiratory_disease_pathogen_diagnosis_complete,levels=c("0","1","2"))
data$daily_mbperf = factor(data$daily_mbperf,levels=c("1","0"))
data$mbspec = factor(data$mbspec,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","15","14"))
data$mbmethod = factor(data$mbmethod,levels=c("1","2","3"))
data$mborres = factor(data$mborres,levels=c("1","2","3"))
data$infectious_respiratory_disease_pathogen_testing_complete = factor(data$infectious_respiratory_disease_pathogen_testing_complete,levels=c("0","1","2"))
data$antiviral_cmyn = factor(data$antiviral_cmyn,levels=c("1","2","3"))
data$antiviral_cmtrt___1 = factor(data$antiviral_cmtrt___1,levels=c("0","1"))
data$antiviral_cmtrt___2 = factor(data$antiviral_cmtrt___2,levels=c("0","1"))
data$antiviral_cmtrt___3 = factor(data$antiviral_cmtrt___3,levels=c("0","1"))
data$antiviral_cmtrt___4 = factor(data$antiviral_cmtrt___4,levels=c("0","1"))
data$antiviral_cmtrt___7 = factor(data$antiviral_cmtrt___7,levels=c("0","1"))
data$antiviral_cmtrt___8 = factor(data$antiviral_cmtrt___8,levels=c("0","1"))
data$antiviral_cmtrt___9 = factor(data$antiviral_cmtrt___9,levels=c("0","1"))
data$antiviral_cmtrt___5 = factor(data$antiviral_cmtrt___5,levels=c("0","1"))
data$antiviral_cmtrt___6 = factor(data$antiviral_cmtrt___6,levels=c("0","1"))
data$il6_cmtrt = factor(data$il6_cmtrt,levels=c("1","2","3","10"))
data$othantiviral2_cmyn = factor(data$othantiviral2_cmyn,levels=c("1","0"))
data$othantiviral3_cmyn = factor(data$othantiviral3_cmyn,levels=c("1","0"))
data$othantiviral4_cmyn = factor(data$othantiviral4_cmyn,levels=c("1","0"))
data$othantiviral5_cmyn = factor(data$othantiviral5_cmyn,levels=c("1","0"))
data$antibiotic_cmyn = factor(data$antibiotic_cmyn,levels=c("1","2","3"))
data$antibiotic2_cmyn = factor(data$antibiotic2_cmyn,levels=c("1","2","3"))
data$antibiotic3_cmyn = factor(data$antibiotic3_cmyn,levels=c("1","2","3"))
data$antibiotic4_cmyn = factor(data$antibiotic4_cmyn,levels=c("1","2","3"))
data$antibiotic5_cmyn = factor(data$antibiotic5_cmyn,levels=c("1","2","3"))
data$antibiotic6_cmyn = factor(data$antibiotic6_cmyn,levels=c("1","2","3"))
data$antibiotic7_cmyn = factor(data$antibiotic7_cmyn,levels=c("1","2","3"))
data$corticost_cmyn = factor(data$corticost_cmyn,levels=c("1","2","3"))
data$corticost_cmroute = factor(data$corticost_cmroute,levels=c("1","2","3"))
data$corticost2_cmyn = factor(data$corticost2_cmyn,levels=c("1","2","3"))
data$corticost2_cmroute = factor(data$corticost2_cmroute,levels=c("1","2","3"))
data$corticost3_cmyn = factor(data$corticost3_cmyn,levels=c("1","2","3"))
data$corticost3_cmroute = factor(data$corticost3_cmroute,levels=c("1","2","3"))
data$dexamethasone = factor(data$dexamethasone,levels=c("1","2","3"))
data$dexamethasone_route = factor(data$dexamethasone_route,levels=c("1","2"))
data$antifung_cmyn = factor(data$antifung_cmyn,levels=c("1","2","3"))
data$offlabel_cmyn = factor(data$offlabel_cmyn,levels=c("1","2","3"))
data$interleukin_cmyn = factor(data$interleukin_cmyn,levels=c("1","2","3"))
data$conv_plasma_cmyn = factor(data$conv_plasma_cmyn,levels=c("1","2","3"))
data$icu_hoterm = factor(data$icu_hoterm,levels=c("1","2","3"))
data$oxygen_cmoccur = factor(data$oxygen_cmoccur,levels=c("1","2","3"))
data$oxygenhf_cmoccur = factor(data$oxygenhf_cmoccur,levels=c("1","2","3"))
data$noninvasive_proccur = factor(data$noninvasive_proccur,levels=c("1","2","3"))
data$invasive_proccur = factor(data$invasive_proccur,levels=c("1","2","3"))
data$pronevent_prtrt = factor(data$pronevent_prtrt,levels=c("1","2","3"))
data$inhalednit_cmtrt = factor(data$inhalednit_cmtrt,levels=c("1","2","3"))
data$tracheo_prtrt = factor(data$tracheo_prtrt,levels=c("1","2","3"))
data$extracorp_prtrt = factor(data$extracorp_prtrt,levels=c("1","2","3"))
data$rrt_prtrt = factor(data$rrt_prtrt,levels=c("1","2","3"))
data$inotrop_cmtrt = factor(data$inotrop_cmtrt,levels=c("1","2","3"))
data$other_cmyn = factor(data$other_cmyn,levels=c("1","2","3"))
data$bloodgroup = factor(data$bloodgroup,levels=c("1","2","3","4","9"))
data$treatment_complete = factor(data$treatment_complete,levels=c("0","1","2"))
data$vrialpneu_ceoccur = factor(data$vrialpneu_ceoccur,levels=c("1","2","3"))
data$bactpneu_ceoccur = factor(data$bactpneu_ceoccur,levels=c("1","2","3"))
data$ards_ceoccur = factor(data$ards_ceoccur,levels=c("1","2","3"))
data$cryptogenic_ceterm = factor(data$cryptogenic_ceterm,levels=c("1","2","3"))
data$pneumothorax_ceterm = factor(data$pneumothorax_ceterm,levels=c("1","2","3"))
data$pleuraleff_ceterm = factor(data$pleuraleff_ceterm,levels=c("1","2","3"))
data$bronchio_ceterm = factor(data$bronchio_ceterm,levels=c("1","2","3"))
data$meningitis_ceterm = factor(data$meningitis_ceterm,levels=c("1","2","3"))
data$seizure_ceterm = factor(data$seizure_ceterm,levels=c("1","2","3"))
data$stroke_ceterm = factor(data$stroke_ceterm,levels=c("1","2","3"))
data$neuro_comp = factor(data$neuro_comp,levels=c("1","2","3"))
data$heartfailure_ceterm = factor(data$heartfailure_ceterm,levels=c("1","2","3"))
data$endocarditis_aeterm = factor(data$endocarditis_aeterm,levels=c("1","2","3"))
data$myocarditis_ceterm = factor(data$myocarditis_ceterm,levels=c("1","2","3"))
data$cardiomyopathy_ceterm = factor(data$cardiomyopathy_ceterm,levels=c("1","2","3"))
data$arrhythmia_ceterm = factor(data$arrhythmia_ceterm,levels=c("1","2","3"))
data$ischaemia_ceterm = factor(data$ischaemia_ceterm,levels=c("1","2","3"))
data$cardiacarrest_ceterm = factor(data$cardiacarrest_ceterm,levels=c("1","2","3"))
data$bacteraemia_ceterm = factor(data$bacteraemia_ceterm,levels=c("1","2","3"))
data$coagulo_ceterm = factor(data$coagulo_ceterm,levels=c("1","2","3"))
data$aneamia_ceterm = factor(data$aneamia_ceterm,levels=c("1","2","3"))
data$rhabdomyolsis_ceterm = factor(data$rhabdomyolsis_ceterm,levels=c("1","2","3"))
data$renalinjury_ceterm = factor(data$renalinjury_ceterm,levels=c("1","2","3"))
data$gastro_ceterm = factor(data$gastro_ceterm,levels=c("1","2","3"))
data$pancreat_ceterm = factor(data$pancreat_ceterm,levels=c("1","2","3"))
data$liverdysfunction_ceterm = factor(data$liverdysfunction_ceterm,levels=c("1","2","3"))
data$hyperglycemia_aeterm = factor(data$hyperglycemia_aeterm,levels=c("1","2","3"))
data$hypoglycemia_ceterm = factor(data$hypoglycemia_ceterm,levels=c("1","2","3"))
data$other_ceoccur = factor(data$other_ceoccur,levels=c("1","2","3"))
data$complications_complete = factor(data$complications_complete,levels=c("0","1","2"))
data$recruitment = factor(data$recruitment,levels=c("1","0"))
data$study_2 = factor(data$study_2,levels=c("1","0"))
data$study_3 = factor(data$study_3,levels=c("1","0"))
data$study_participation_complete = factor(data$study_participation_complete,levels=c("0","1","2"))
data$dsterm = factor(data$dsterm,levels=c("1","2","3","4","5","6"))
data$dshosp = factor(data$dshosp,levels=c("1","2"))
data$dsstdtcyn = factor(data$dsstdtcyn,levels=c("1","2","3"))
data$suppds_qval = factor(data$suppds_qval,levels=c("1","2","3","4"))
data$oxygen_proccur = factor(data$oxygen_proccur,levels=c("1","2","3"))
data$renal_proccur = factor(data$renal_proccur,levels=c("1","2","3"))
data$other_cmoccur = factor(data$other_cmoccur,levels=c("1","2","3"))
data$siteidnk = factor(data$siteidnk,levels=c("1"))
data$siteyn = factor(data$siteyn,levels=c("1","2","3"))
data$subjidcat = factor(data$subjidcat,levels=c("1","2","3"))
data$outcome_complete = factor(data$outcome_complete,levels=c("0","1","2"))
data$core_additional_information_complete = factor(data$core_additional_information_complete,levels=c("0","1","2"))
data$withdtype = factor(data$withdtype,levels=c("1","10"))
data$withdrawal_form_complete = factor(data$withdrawal_form_complete,levels=c("0","1","2"))
data$consent_given = factor(data$consent_given,levels=c("1","0"))
data$consent_mode___1 = factor(data$consent_mode___1,levels=c("0","1"))
data$consent_mode___2 = factor(data$consent_mode___2,levels=c("0","1"))
data$consent_mode___3 = factor(data$consent_mode___3,levels=c("0","1"))
data$consent_mode___4 = factor(data$consent_mode___4,levels=c("0","1"))
data$consent_mode___5 = factor(data$consent_mode___5,levels=c("0","1"))
data$consent_mode___6 = factor(data$consent_mode___6,levels=c("0","1"))
data$consent_mode___7 = factor(data$consent_mode___7,levels=c("0","1"))
data$consent_mode___8 = factor(data$consent_mode___8,levels=c("0","1"))
data$consent_mode___9 = factor(data$consent_mode___9,levels=c("0","1"))
data$consent_mode___10 = factor(data$consent_mode___10,levels=c("0","1"))
data$consent_mode___11 = factor(data$consent_mode___11,levels=c("0","1"))
data$consent_optcondit___1 = factor(data$consent_optcondit___1,levels=c("0","1"))
data$consent_optcondit___2 = factor(data$consent_optcondit___2,levels=c("0","1"))
data$consent_optcondit___3 = factor(data$consent_optcondit___3,levels=c("0","1"))
data$consent_optcondit___4 = factor(data$consent_optcondit___4,levels=c("0","1"))
data$consent_ctu_dms_complete = factor(data$consent_ctu_dms_complete,levels=c("0","1","2"))

levels(data$redcap_event_name)=c("Day 1 Hospital Admission (Arm 1: TIER 0)","Day 3 (Arm 1: TIER 0)","Day 6 (Arm 1: TIER 0)","Day 9 (Arm 1: TIER 0)","Additional days (Arm 1: TIER 0)","Discharge/Death (Arm 1: TIER 0)","Day 1 Hospital&ICU Admission (Arm 2: TIER 1)","Day 3 (Arm 2: TIER 1)","Day 6 (Arm 2: TIER 1)","Day 9 (Arm 2: TIER 1)","Additional days (Arm 2: TIER 1)","Discharge/Death (Arm 2: TIER 1)","Day 1 (Arm 3: TIER 2)","Day 2 (Arm 3: TIER 2)","Day 3 (Arm 3: TIER 2)","Day 4 (Arm 3: TIER 2)","Day 5 (Arm 3: TIER 2)","Day 6 (Arm 3: TIER 2)","Day 7 (Arm 3: TIER 2)","Day 8 (Arm 3: TIER 2)","Day 9 (Arm 3: TIER 2)","Day 10 (Arm 3: TIER 2)","Day 11 (Arm 3: TIER 2)","Day 12 (Arm 3: TIER 2)","Day 13 (Arm 3: TIER 2)","Day 14 (Arm 3: TIER 2)","Additional days (Arm 3: TIER 2)","Discharge/Death (Arm 3: TIER 2)")
levels(data$redcap_repeat_instrument)=c("Pre-admission medication","Infectious Respiratory Disease Pathogen Testing","Daily Form")
levels(data$tiers_faorres___1)=c("Unchecked","Checked")
levels(data$tiers_faorres___2)=c("Unchecked","Checked")
levels(data$tiers_faorres___3)=c("Unchecked","Checked")
levels(data$tiers_consent_complete)=c("Incomplete","Unverified","Complete")
levels(data$participant_identification_number_pin_complete)=c("Incomplete","Unverified","Complete")
levels(data$covid19_new)=c("Data in new COVID-19 short CRF")
levels(data$corona_ieorres)=c("Yes","No")
levels(data$coriona_ieorres2)=c("Yes","No")
levels(data$fever)=c("Yes","No")
levels(data$cough)=c("Yes","No")
levels(data$dyspnoe)=c("Yes","No")
levels(data$ari)=c("Yes","No")
levels(data$symptoms_epi_travel)=c("YES","NO","Unknown")
levels(data$symptoms_epi_physical)=c("YES","NO","Unknown")
levels(data$symptoms_epi_healthfac)=c("YES","NO","Unknown")
levels(data$symptoms_epi_lab)=c("YES","NO","Unknown")
levels(data$symptoms_epi_pathogen)=c("YES","NO","Unknown")
levels(data$symptoms_epi_animal)=c("YES","NO","Unknown")
levels(data$inclusion_criteria_complete)=c("Incomplete","Unverified","Complete")
levels(data$sex)=c("Male","Female","Not specified")
levels(data$agedatyn)=c("Yes","No")
levels(data$age_estimateyearsu)=c("Months","Years")
levels(data$ethnic___1)=c("Unchecked","Checked")
levels(data$ethnic___2)=c("Unchecked","Checked")
levels(data$ethnic___3)=c("Unchecked","Checked")
levels(data$ethnic___4)=c("Unchecked","Checked")
levels(data$ethnic___5)=c("Unchecked","Checked")
levels(data$ethnic___6)=c("Unchecked","Checked")
levels(data$ethnic___7)=c("Unchecked","Checked")
levels(data$ethnic___8)=c("Unchecked","Checked")
levels(data$ethnic___9)=c("Unchecked","Checked")
levels(data$ethnic___10)=c("Unchecked","Checked")
levels(data$healthwork_erterm)=c("YES","NO","N/A")
levels(data$labwork_erterm)=c("YES","NO","N/A")
levels(data$pregyn_rptestcd)=c("YES","NO","Unknown","N/A")
levels(data$postpart_rptestcd)=c("Yes","No","N/K")
levels(data$pregout_rptestcd)=c("Live birth","Still birth")
levels(data$aplb_lbperf)=c("Yes","No","N/A")
levels(data$aplb_lborres)=c("Positive","Negative")
levels(data$aplb_lbmethod)=c("PCR","Other")
levels(data$apdm_age)=c("Yes","No")
levels(data$apvs_weightu)=c("kg","lbs")
levels(data$apvs_weightnk)=c("N/K")
levels(data$apsc_gestout)=c("Term birth ( >= 37wk GA)","Preterm birth (< 37wk GA)","N/A")
levels(data$apsc_brfedind)=c("Yes","No","N/A")
levels(data$apsc_brfedindy)=c("Currently breastfed","Breastfeeding discontinued","N/A")
levels(data$apsc_dvageind)=c("Yes","No","N/A")
levels(data$apsc_vcageind)=c("Yes","No","Unknown","N/A")
levels(data$demographics_complete)=c("Incomplete","Unverified","Complete")
levels(data$readm_cov19)=c("Yes","No","N/K")
levels(data$readminreasnk)=c("N/K")
levels(data$surgefacil)=c("Yes","No","N/K")
levels(data$hooccur)=c("Yes-other facility is a study site","Yes-other facility is not a study site","No","N/A")
levels(data$siteid_transfernk)=c("N/K")
levels(data$hostdat_transfernk)=c("N/K")
levels(data$subjidcat_transfer)=c("Same as above","Different","N/A")
levels(data$travel_erterm)=c("Yes","No","N/A")
levels(data$supper_trcntry)=c("Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas (The)","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burma","Burundi","Cambodia","Cameroon","Canada","Cabo Verde","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo (Republic of the)","Costa Rica","Cote dIvoire","Croatia","Cuba","Curacao","Cyprus","Czechia","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Ethiopia","Fiji","Finland","France","Gabon","Gambia (The)","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Holy See","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Korea (South)","Kosovo","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea","Norway","Oman","Pakistan","Palau","Palestinian Territories","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Sint Maarten","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe")
levels(data$travel_erterm_2)=c("Yes","No","N/A")
levels(data$supper_trcntry_2)=c("Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas (The)","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burma","Burundi","Cambodia","Cameroon","Canada","Cabo Verde","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo (Republic of the)","Costa Rica","Cote dIvoire","Croatia","Cuba","Curacao","Cyprus","Czechia","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Ethiopia","Fiji","Finland","France","Gabon","Gambia (The)","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Holy See","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Korea (South)","Kosovo","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea","Norway","Oman","Pakistan","Palau","Palestinian Territories","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Sint Maarten","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe")
levels(data$animal_eryn)=c("Yes","No","Unknown","N/A")
levels(data$animal_eryn_2)=c("Yes","No","Unknown","N/A")
levels(data$onset_and_admission_complete)=c("Incomplete","Unverified","Complete")
levels(data$temp_vsyn)=c("Yes","No")
levels(data$temp_vsorresu)=c("°C","°F")
levels(data$hr_vsyn)=c("Yes","No")
levels(data$rr_vsyn)=c("Yes","No")
levels(data$sysbp_vsyn)=c("Yes","No")
levels(data$diabp_vsyn)=c("Yes","No")
levels(data$dehydration_vsorres)=c("Yes","No","Unknown")
levels(data$stercap_vsyn)=c("Yes","No")
levels(data$stercap_vsorres)=c("Yes","No","Unknown")
levels(data$oxy_vsyn)=c("Yes","No")
levels(data$oxy_vsorresu)=c("Room air","Oxygen therapy","N/A")
levels(data$fever_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$cough_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$coughsput_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$coughhb_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$sorethroat_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$runnynose_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$earpain_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$wheeze_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$chestpain_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$myalgia_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$jointpain_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$fatigue_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$shortbreath_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$ageusia_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$lowerchest_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$headache_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$confusion_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$seizures_cecoccur_v2)=c("YES","NO","Unknown")
levels(data$abdopain_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$vomit_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$diarrhoea_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$conjunct_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$rash_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$skinulcers_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$lymp_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$bleed_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$bleed_ceterm_v2)=c("YES","NO","Unknown")
levels(data$anosmia_ceoccur_v2)=c("YES","NO","Unknown")
levels(data$admission_signs_and_symptoms_complete)=c("Incomplete","Unverified","Complete")
levels(data$chrincard)=c("YES","NO","Unknown")
levels(data$hypertension_mhyn)=c("YES","NO","Unknown")
levels(data$chronicpul_mhyn)=c("YES","NO","Unknown")
levels(data$asthma_mhyn)=c("YES","NO","Unknown")
levels(data$renal_mhyn)=c("YES","NO","Unknown")
levels(data$modliv)=c("YES","NO","Unknown")
levels(data$mildliver)=c("YES","NO","Unknown")
levels(data$chronicneu_mhyn)=c("YES","NO","Unknown")
levels(data$malignantneo_mhyn)=c("YES","NO","Unknown")
levels(data$chronichaemo_mhyn)=c("YES","NO","Unknown")
levels(data$aidshiv_mhyn)=c("YES","NO","Unknown")
levels(data$obesity_mhyn)=c("YES","NO","Unknown")
levels(data$diabetes_type_mhyn)=c("NO","1","2","N/K")
levels(data$diabetescom_mhyn)=c("YES","NO","Unknown")
levels(data$diabetes_mhyn)=c("YES","NO","Unknown")
levels(data$rheumatologic_mhyn)=c("YES","NO","Unknown")
levels(data$dementia_mhyn)=c("YES","NO","Unknown")
levels(data$malnutrition_mhyn)=c("YES","NO","Unknown")
levels(data$smoking_mhyn)=c("Yes","Never Smoked","Former Smoker","N/K")
levels(data$other_mhyn)=c("Yes","No","Unknown")
levels(data$vulnerable_transplant)=c("Yes","No","N/K")
levels(data$vulnerable_cancers)=c("Yes","No","N/K")
levels(data$vulnerable_copd)=c("Yes","No","N/K")
levels(data$vulnerable_scid)=c("Yes","No","N/K")
levels(data$vulnerable_immuno)=c("Yes","No","N/K")
levels(data$vulnerable_preg)=c("Yes","No","N/K")
levels(data$comorbidities_complete)=c("Incomplete","Unverified","Complete")
levels(data$immno_cmtrt)=c("Yes","No","N/A")
levels(data$infect_cmtrt)=c("Yes","No","N/A")
levels(data$chronic_ace_cmoccur)=c("Yes","No","N/K")
levels(data$chronic_arb_cmoccur)=c("Yes","No","N/K")
levels(data$chronic_nsaid_cmoccur)=c("Yes","No","N/K")
levels(data$clinical_frailty)=c("1","2","3","4","5","6","7","8","9","N/K")
levels(data$preadmission_treatment_complete)=c("Incomplete","Unverified","Complete")
levels(data$cmdose_unit)=c("microgram","milligram","gram","int. unit","other","Unknown")
levels(data$cmdosfrq)=c("q.d - once a day","b.i.d - twice a day","t.i.d - three times a day","q.i.d - four times a day","q.h.s - before bed","5X a day - five times a day","q.4h - every four hours","q.6h - every six hours","q.o.d - every other day","prn - as needed","Other frequency","Unknown")
levels(data$cmroute)=c("IV","oral","Inhaled","Unknown","Other")
levels(data$preadmission_medication_complete)=c("Incomplete","Unverified","Complete")
levels(data$daily_hoterm)=c("Yes","No","N/A")
levels(data$daily_temp_vsorresu)=c("°C","°F")
levels(data$daily_temp_vsorresnk)=c("N/K")
levels(data$daily_fi02_lbyn)=c("Yes","No","N/K")
levels(data$daily_sa02_lbyn)=c("Yes","No","N/K")
levels(data$daily_pao2_lbyn)=c("Yes","No")
levels(data$daily_pao2_lborresu)=c("kPa","mmHg")
levels(data$daily_pao2_lbspec)=c("Arterial","Venous","Capillary","N/A")
levels(data$daily_pco2_lbyn)=c("Yes","No")
levels(data$daily_pco2_lborresu)=c("kPa","mmHg")
levels(data$daily_ph_lbyn)=c("Yes","No")
levels(data$daily_hco3_lbyn)=c("Yes","No")
levels(data$daily_baseex_lbyn)=c("Yes","No")
levels(data$avpu_vsorres)=c("Alert","Verbal","Pain","Unresponsive","N/K")
levels(data$daily_gcs_lbyn)=c("Yes","No","N/K")
levels(data$systolic_vsyn)=c("Yes","No")
levels(data$diastolic_vsyn)=c("Yes","No")
levels(data$daily_meanart_lbyn)=c("Yes","No")
levels(data$daily_urine_lbyn)=c("Yes","Estimated","No")
levels(data$daily_noninvasive_prtrt)=c("YES","NO","N/A")
levels(data$daily_invasive_prtrt)=c("YES","NO","N/A")
levels(data$daily_nasaloxy_cmtrt)=c("YES","NO","N/A")
levels(data$daily_ecmo_prtrt)=c("YES","NO","N/A")
levels(data$daily_rrt_cmtrt)=c("YES","NO","N/A")
levels(data$daily_inotrope_cmyn)=c("YES","NO","N/A")
levels(data$daily_dopless5_cmtrt)=c("YES","NO","N/A")
levels(data$daily_dop5to15_cmtrt)=c("YES","NO","N/A")
levels(data$daily_dopgr15_cmtrt)=c("YES","NO","N/A")
levels(data$daily_neuro_cmtrt)=c("YES","NO","N/A")
levels(data$daily_nitritc_cmtrt)=c("YES","NO","N/A")
levels(data$daily_prone_cmtrt)=c("YES","NO","N/A")
levels(data$daily_trach_prperf)=c("YES","NO","N/A")
levels(data$daily_prperf)=c("YES","NO","N/A")
levels(data$daily_lbperf)=c("Yes","No")
levels(data$daily_hb_lbyn)=c("Yes","No","N/K")
# changed c("") (REDCap bug around weird levels) to c("<", ">") here and on similar variables below 
levels(data$daily_hbop_lborres)=c("<", ">")
levels(data$daily_hb_lborresu)=c("g/L","g/dL")
levels(data$daily_wbc_lbyn)=c("Yes","No","N/K")
levels(data$daily_wbcop_lborres)=c("<", ">")
levels(data$daily_wbc_lborresu)=c("x 10^9 / L","x 103/µL")
levels(data$daily_lymp_lbyn)=c("Yes","No","N/K")
levels(data$daily_lympop_lbyn)=c("<", ">")
levels(data$daily_lymp_lborresu)=c("cells/ μL","x 10^9 / L","x 10³/μL")
levels(data$daily_neutro_lbyn)=c("Yes","No","N/K")
levels(data$daily_neutroop_lbyn)=c("<", ">")
levels(data$daily_neutro_lborresu)=c("cells/ μL","x 10^9 / L","x 10³/μL")
levels(data$daily_haematocrit_lbyn)=c("Yes","No")
levels(data$daily_plt_lbyn)=c("Yes","No","N/K")
levels(data$daily_pltop_lborres)=c("<", ">")
levels(data$daily_plt_lborresu)=c("x 10^9 / L","x 103/μL")
levels(data$daily_aptt_lbyn)=c("Yes","No","N/K")
levels(data$daily_apttop_lborres)=c("<", ">")
levels(data$daily_pt_inr_lbyn)=c("PT done","INR done","PT or INR not done","N/K")
levels(data$daily_ptop_lborres)=c("<", ">")
levels(data$daily_inrop_lborres)=c("<", ">")
levels(data$daily_alt_lbyn)=c("Yes","No","N/K")
levels(data$daily_altop_lbyn)=c("<", ">")
levels(data$daily_bil_lbyn)=c("Yes","No","N/K")
levels(data$daily_bilop_lborres)=c("<", ">")
levels(data$daily_bil_lborresu)=c("µmol/L","mg/dL")
levels(data$daily_ast_lbyn)=c("Yes","No","N/K")
levels(data$daily_astop_lborres)=c("<", ">")
levels(data$daily_glucose_lbyn)=c("Yes","No","N/K")
levels(data$daily_glucoseop_lborres)=c("<", ">")
levels(data$daily_glucose_lborresu)=c("mmol/L","mg/dL")
levels(data$daily_bun_lbyn)=c("Yes","No","N/K")
levels(data$daily_bunop_lborres)=c("<", ">")
levels(data$daily_bun_lborresu)=c("mmol/L","mg/dL")
levels(data$daily_lactate_lbyn)=c("Yes","No","N/K")
levels(data$daily_lactateop_lbyn)=c("<", ">")
levels(data$daily_lactate_lborresu)=c("mmol/L","mg/dL")
levels(data$daily_ldh_lbyn)=c("Yes","No","N/K")
levels(data$daily_ldhop_lborres)=c("<", ">")
levels(data$daily_cpk_lby)=c("Yes","No","N/K")
levels(data$daily_cpkop_lbyn_2)=c("<", ">")
levels(data$daily_creat_lbyn)=c("Yes","No","N/K")
levels(data$daily_creatop_lborres)=c("<", ">")
levels(data$daily_creat_lborresu)=c("μmol/L","mg/dL","umol/L")
levels(data$daily_sodium_lbyn)=c("Yes","No","N/K")
levels(data$daily_sodiumop_lborres)=c("<", ">")
levels(data$daily_sodium_lborresu)=c("mmol/L","mEq/L")
levels(data$daily_potassium_lbyn)=c("Yes","No","N/K")
levels(data$daily_potassiumop_lborres)=c("<", ">")
levels(data$daily_potassium_lborresu)=c("mmol/L","mEq/L")
levels(data$daily_procal_lbyn)=c("Yes","No","N/K")
levels(data$daily_procalop_lborres)=c("<", ">")
levels(data$daily_crp_lbyn)=c("Yes","No","N/K")
levels(data$daily_crpop_lborres)=c("<", ">")
levels(data$daily_crp_lborresu)=c("mg/L","mg/dL","ug/ml")
levels(data$daily_hba1cop_lborres)=c("<", ">")
levels(data$daily_hba1c_lborresnk)=c("N/K")
levels(data$xray_prperf)=c("YES","NO","N/A")
levels(data$infiltrates_faorres)=c("YES","NO","N/A")
levels(data$daily_form_complete)=c("Incomplete","Unverified","Complete")
levels(data$ni_site)=c("Yes")
levels(data$inflammatory_mss)=c("Yes","No")
levels(data$asymptomatic)=c("Asymptomatic")
levels(data$no_symptoms)=c("YES","NO","Unknown")
levels(data$no_medication)=c("No medication currently or within the last 14 days")
levels(data$daily_hco3_lborresu)=c("mEq/L","mmol/L")
levels(data$remdesivir)=c("YES","NO","N/K")
levels(data$remdesivir_last_dose)=c("YES","NO","N/K")
levels(data$daily_haematocrit_lborresu)=c("%","L/L")
levels(data$daily_esr_lbyn)=c("Yes","No","N/K")
levels(data$daily_esrop_lbyn)=c("<", ">")
levels(data$daily_ferr_lbyn)=c("Yes","No","N/K")
levels(data$daily_ferrop_lbyn)=c("<", ">")
levels(data$daily_ferr_lborresu)=c("μg/L","ng/mL")
levels(data$daily_egfr_lbyn)=c("Yes","No","N/K")
levels(data$daily_egfrop_lborres)=c("<", ">")
levels(data$daily_egfr_equation___1)=c("Unchecked","Checked")
levels(data$daily_egfr_equation___2)=c("Unchecked","Checked")
levels(data$daily_egfr_equation___3)=c("Unchecked","Checked")
levels(data$daily_hba1c_lborresu)=c("%","mmol/mol")
levels(data$mbperf)=c("YES","NO","N/A")
levels(data$influ_mbyn)=c("YES - Confirmed","YES - Probable","NO")
levels(data$influ_mbcat)=c("A/H3N2","A/H1N1pdm09","A/H7N9","A/H5N1","A - not typed","Other A","B - not typed","Other")
levels(data$corna_mbcat)=c("YES - Confirmed","YES - Probable","NO")
levels(data$corna_mbcaty)=c("MERS-CoV","2019nCoV","COVID-19/SARS-CoV-2 2019","Other CoV")
levels(data$rsv_mbcat)=c("YES - Confirmed","YES - Probable","NO")
levels(data$adeno_mbcat)=c("YES - Confirmed","YES - Probable","NO")
levels(data$bact_mborres)=c("YES-Confirmed","NO")
levels(data$other_mbyn)=c("YES - Confirmed","YES - Probable","NO")
levels(data$clinicalpneu_mborres)=c("YES","NO","Unknown")
levels(data$infectuk_mborres)=c("Yes","N/A")
levels(data$infectious_respiratory_disease_pathogen_diagnosis_complete)=c("Incomplete","Unverified","Complete")
levels(data$daily_mbperf)=c("Yes","No")
levels(data$mbspec)=c("Nasal / NP swab","Throat swab","Combined nasal / NP + throat swab","Sputum","Bronchoalveolar Lavage (BAL)","Exotoxin A (ETA)","CSF","SAM","Urine","Faeces / rectal swab","Blood serum","Blood EDTA","Blood RNA","Blood","Other")
levels(data$mbmethod)=c("PCR","Culture","Other")
levels(data$mborres)=c("Positive","Negative","N/A")
levels(data$infectious_respiratory_disease_pathogen_testing_complete)=c("Incomplete","Unverified","Complete")
levels(data$antiviral_cmyn)=c("Yes","No","N/A")
levels(data$antiviral_cmtrt___1)=c("Unchecked","Checked")
levels(data$antiviral_cmtrt___2)=c("Unchecked","Checked")
levels(data$antiviral_cmtrt___3)=c("Unchecked","Checked")
levels(data$antiviral_cmtrt___4)=c("Unchecked","Checked")
levels(data$antiviral_cmtrt___7)=c("Unchecked","Checked")
levels(data$antiviral_cmtrt___8)=c("Unchecked","Checked")
levels(data$antiviral_cmtrt___9)=c("Unchecked","Checked")
levels(data$antiviral_cmtrt___5)=c("Unchecked","Checked")
levels(data$antiviral_cmtrt___6)=c("Unchecked","Checked")
levels(data$il6_cmtrt)=c("Tocilizumab","Anakinra","drug X","Other IL6 inhibitor")
levels(data$othantiviral2_cmyn)=c("Yes","No")
levels(data$othantiviral3_cmyn)=c("Yes","No")
levels(data$othantiviral4_cmyn)=c("Yes","No")
levels(data$othantiviral5_cmyn)=c("Yes","No")
levels(data$antibiotic_cmyn)=c("Yes","No","N/A")
levels(data$antibiotic2_cmyn)=c("Yes","No","N/A")
levels(data$antibiotic3_cmyn)=c("Yes","No","N/A")
levels(data$antibiotic4_cmyn)=c("Yes","No","N/A")
levels(data$antibiotic5_cmyn)=c("Yes","No","N/A")
levels(data$antibiotic6_cmyn)=c("Yes","No","N/A")
levels(data$antibiotic7_cmyn)=c("Yes","No","N/A")
levels(data$corticost_cmyn)=c("Yes","No","N/A")
levels(data$corticost_cmroute)=c("Oral","Intravenous","Inhaled")
levels(data$corticost2_cmyn)=c("Yes","No","N/A")
levels(data$corticost2_cmroute)=c("Oral","Intravenous","Inhaled")
levels(data$corticost3_cmyn)=c("Yes","No","N/A")
levels(data$corticost3_cmroute)=c("Oral","Intravenous","Inhaled")
levels(data$dexamethasone)=c("Yes","No","N/K")
levels(data$dexamethasone_route)=c("Oral","Intravenous")
levels(data$antifung_cmyn)=c("Yes","No","N/A")
levels(data$offlabel_cmyn)=c("Yes","No","N/K")
levels(data$interleukin_cmyn)=c("Yes","No","N/K")
levels(data$conv_plasma_cmyn)=c("Yes","No","N/K")
levels(data$icu_hoterm)=c("Yes","No","N/A")
levels(data$oxygen_cmoccur)=c("YES","NO","N/A")
levels(data$oxygenhf_cmoccur)=c("YES","NO","N/A")
levels(data$noninvasive_proccur)=c("YES","NO","N/A")
levels(data$invasive_proccur)=c("YES","NO","N/A")
levels(data$pronevent_prtrt)=c("YES","NO","N/A")
levels(data$inhalednit_cmtrt)=c("YES","NO","N/A")
levels(data$tracheo_prtrt)=c("YES","NO","N/A")
levels(data$extracorp_prtrt)=c("YES","NO","N/A")
levels(data$rrt_prtrt)=c("YES","NO","N/A")
levels(data$inotrop_cmtrt)=c("YES","NO","N/A")
levels(data$other_cmyn)=c("YES","NO","N/A")
levels(data$bloodgroup)=c("A","B","AB","O","N/K")
levels(data$treatment_complete)=c("Incomplete","Unverified","Complete")
levels(data$vrialpneu_ceoccur)=c("YES","NO","N/A")
levels(data$bactpneu_ceoccur)=c("YES","NO","N/A")
levels(data$ards_ceoccur)=c("YES","NO","N/A")
levels(data$cryptogenic_ceterm)=c("YES","NO","N/A")
levels(data$pneumothorax_ceterm)=c("YES","NO","N/A")
levels(data$pleuraleff_ceterm)=c("YES","NO","N/A")
levels(data$bronchio_ceterm)=c("YES","NO","N/A")
levels(data$meningitis_ceterm)=c("YES","NO","N/A")
levels(data$seizure_ceterm)=c("YES","NO","N/A")
levels(data$stroke_ceterm)=c("YES","NO","N/A")
levels(data$neuro_comp)=c("YES","NO","N/A")
levels(data$heartfailure_ceterm)=c("YES","NO","N/A")
levels(data$endocarditis_aeterm)=c("YES","NO","N/A")
levels(data$myocarditis_ceterm)=c("YES","NO","N/A")
levels(data$cardiomyopathy_ceterm)=c("YES","NO","N/A")
levels(data$arrhythmia_ceterm)=c("YES","NO","N/A")
levels(data$ischaemia_ceterm)=c("YES","NO","N/A")
levels(data$cardiacarrest_ceterm)=c("YES","NO","N/A")
levels(data$bacteraemia_ceterm)=c("YES","NO","N/A")
levels(data$coagulo_ceterm)=c("YES","NO","N/A")
levels(data$aneamia_ceterm)=c("YES","NO","N/A")
levels(data$rhabdomyolsis_ceterm)=c("YES","NO","N/A")
levels(data$renalinjury_ceterm)=c("YES","NO","N/A")
levels(data$gastro_ceterm)=c("YES","NO","N/A")
levels(data$pancreat_ceterm)=c("YES","NO","N/A")
levels(data$liverdysfunction_ceterm)=c("YES","NO","N/A")
levels(data$hyperglycemia_aeterm)=c("YES","NO","N/A")
levels(data$hypoglycemia_ceterm)=c("YES","NO","N/A")
levels(data$other_ceoccur)=c("YES","NO","N/A")
levels(data$complications_complete)=c("Incomplete","Unverified","Complete")
levels(data$recruitment)=c("Yes","No")
levels(data$study_2)=c("Yes","No")
levels(data$study_3)=c("Yes","No")
levels(data$study_participation_complete)=c("Incomplete","Unverified","Complete")
levels(data$dsterm)=c("Discharged alive","Hospitalization","Transfer to other facility","Death","Palliative discharge","Unknown")
levels(data$dshosp)=c("Ongoing health care needs relating to this admission for COVID-19","Medically fit for discharge (COVID-19 resolved) but remains in hospital for other reason (e.g. awaiting suitable care in community, resident in long term health care or mental health facility)")
levels(data$dsstdtcyn)=c("Yes","No","N/A")
levels(data$suppds_qval)=c("Same as before illness","Worse","Better","N/A")
levels(data$oxygen_proccur)=c("YES","NO","N/A")
levels(data$renal_proccur)=c("YES","NO","N/A")
levels(data$other_cmoccur)=c("YES","NO","N/A")
levels(data$siteidnk)=c("N/K")
levels(data$siteyn)=c("Yes","No","N/A")
levels(data$subjidcat)=c("Same as the above","Different","N/K")
levels(data$outcome_complete)=c("Incomplete","Unverified","Complete")
levels(data$core_additional_information_complete)=c("Incomplete","Unverified","Complete")
levels(data$withdtype)=c("Withdrawal from samples only","Other  Please specify:")
levels(data$withdrawal_form_complete)=c("Incomplete","Unverified","Complete")
levels(data$consent_given)=c("Yes","No")
levels(data$consent_mode___1)=c("Unchecked","Checked")
levels(data$consent_mode___2)=c("Unchecked","Checked")
levels(data$consent_mode___3)=c("Unchecked","Checked")
levels(data$consent_mode___4)=c("Unchecked","Checked")
levels(data$consent_mode___5)=c("Unchecked","Checked")
levels(data$consent_mode___6)=c("Unchecked","Checked")
levels(data$consent_mode___7)=c("Unchecked","Checked")
levels(data$consent_mode___8)=c("Unchecked","Checked")
levels(data$consent_mode___9)=c("Unchecked","Checked")
levels(data$consent_mode___10)=c("Unchecked","Checked")
levels(data$consent_mode___11)=c("Unchecked","Checked")
levels(data$consent_optcondit___1)=c("Unchecked","Checked")
levels(data$consent_optcondit___2)=c("Unchecked","Checked")
levels(data$consent_optcondit___3)=c("Unchecked","Checked")
levels(data$consent_optcondit___4)=c("Unchecked","Checked")
levels(data$consent_ctu_dms_complete)=c("Incomplete","Unverified","Complete")

# Setting Labels
# RP changed Hmisc::label code to finalfit::ff_label(label
# 1. Remove `label(` (beginning of each line) - make sure not to remove from these instructions but selection only
# 2. Replace  `)=` with ` %<>% ff_label(`
# 3. Copy to Notepad++ or Atom and replace `\n` with `)\n`
# (so to add `)` to each line closing the ff_label(...
# I couldn't get RStudio's Regex Find-Replace to recognise \n or \\n
# 4. Removed the : from Sex at Birth:

library(finalfit)
library(magrittr)

data$subjid %<>% ff_label("Participant Identification Number (PIN) spe...e.g Y0401-0001.")
data$redcap_event_name %<>% ff_label("Event Name")
data$redcap_repeat_instrument %<>% ff_label("Repeat Instrument")
data$redcap_repeat_instance %<>% ff_label("Repeat Instance")
data$tiers_faorres___1 %<>% ff_label("Please acknowledge that you have understood...entering data. (choice=TIER 0 (data...required.)")
data$tiers_faorres___2 %<>% ff_label("Please acknowledge that you have understood...entering data. (choice=TIER 1 (singl...required.)")
data$tiers_faorres___3 %<>% ff_label("Please acknowledge that you have understood...entering data. (choice=TIER 2 (multi...required.)")
data$tiers_consent_complete %<>% ff_label("Complete?")
data$participant_identification_number_pin_complete %<>% ff_label("Complete?")
data$covid19_new %<>% ff_label("SELECT...")
data$dsstdat %<>% ff_label("Date of Enrolment")
data$sitename %<>% ff_label("Site name")
data$corona_ieorres %<>% ff_label("Suspected or proven infection with pathogen...Health Interest")
data$coriona_ieorres2 %<>% ff_label("Proven or high likelihood of infection with...alth Interest  ")
data$fever %<>% ff_label("A history of self reported feverishness or...er of ≥ 38°C")
data$cough %<>% ff_label("Cough ")
data$dyspnoe %<>% ff_label("Dyspnoea (shortness of breath) OR Tachypnoea*")
data$ari %<>% ff_label("Clinical suspicion of ARI despite not meeting criteria above")
data$symptoms_epi_travel %<>% ff_label("2.A history of travel to an area with docum...virus infection")
data$symptoms_epi_physical %<>% ff_label("3.Close contact* with a confirmed or probab...was symptomatic")
data$symptoms_epi_healthfac %<>% ff_label("4.Presence in a healthcare facility where n...ve been managed")
data$symptoms_epi_lab %<>% ff_label("5. Presence in a laboratory handling sample...nterest present")
data$symptoms_epi_pathogen %<>% ff_label("6.An otherwise unexplained respiratory illn...health interest")
data$symptoms_epi_animal %<>% ff_label("7.Direct contact with animals in countries...ic transmission")
data$inclusion_criteria_complete %<>% ff_label("Complete?")
data$sex %<>% ff_label("Sex at Birth")
data$agedatyn %<>% ff_label("Is birth date known")
data$agedat %<>% ff_label("Birth date (has approval for entry)")
data$calc_age %<>% ff_label("Calculated Age (comparing Date of birth wit...uary 29 is used")
data$age_estimateyears %<>% ff_label("Age/Estimated age")
data$age_estimateyearsu %<>% ff_label("Age/Estimated age Unit")
data$postcode %<>% ff_label("Postcode (has approval for entry)")
data$nhs_chi %<>% ff_label("England & Wales NHS number, Scotland CHI nu...ed at this time")
data$ethnic___1 %<>% ff_label("Ethnic group (check all that apply) (choice=Arab)")
data$ethnic___2 %<>% ff_label("Ethnic group (check all that apply) (choice=Black)")
data$ethnic___3 %<>% ff_label("Ethnic group (check all that apply) (choice=East Asian)")
data$ethnic___4 %<>% ff_label("Ethnic group (check all that apply) (choice=South Asian)")
data$ethnic___5 %<>% ff_label("Ethnic group (check all that apply) (choice=West Asian)")
data$ethnic___6 %<>% ff_label("Ethnic group (check all that apply) (choice=Latin American)")
data$ethnic___7 %<>% ff_label("Ethnic group (check all that apply) (choice=White)")
data$ethnic___8 %<>% ff_label("Ethnic group (check all that apply) (choice=Aboriginal/First Nations)")
data$ethnic___9 %<>% ff_label("Ethnic group (check all that apply) (choice=Other)")
data$ethnic___10 %<>% ff_label("Ethnic group (check all that apply) (choice=N/A)")
data$other_ethnic %<>% ff_label("If Other: Specify")
data$healthwork_erterm %<>% ff_label("Employed as a healthcare worker?")
data$labwork_erterm %<>% ff_label("Employed in a microbiology laboratory?")
data$pregyn_rptestcd %<>% ff_label("Pregnant ?")
data$egestage_rptestcd %<>% ff_label("If YES: Gestational weeks assessment:")
data$postpart_rptestcd %<>% ff_label("Post Partum (within six weeks of delivery)")
data$pregout_rptestcd %<>% ff_label("Pregnancy Outcome")
data$dlvrdtc_rptestcd %<>% ff_label("Delivery date")
data$aplb_lbperf %<>% ff_label("Baby tested for mothers ARI infection")
data$aplb_lborres %<>% ff_label(" If YES")
data$aplb_lbmethod %<>% ff_label("Method")
data$aplb_lbmethodoth %<>% ff_label("If OTHER method; Specify")
data$apdm_age %<>% ff_label("INFANT - Less than 1 year old?")
data$apvs_weight %<>% ff_label("Birth weight")
data$apvs_weightu %<>% ff_label("Birth weight unit")
data$apvs_weightnk %<>% ff_label("Birth weight N/K")
data$apsc_gestout %<>% ff_label("Gestational outcome")
data$estgest %<>% ff_label("If < 37wk  confirm estimated gestation   ")
data$apsc_brfedind %<>% ff_label("Breastfed")
data$apsc_brfedindy %<>% ff_label("If  YES")
data$apsc_brdisdat %<>% ff_label("Discontinued breastfeeding at ")
data$apsc_dvageind %<>% ff_label("Appropriate development for age?")
data$apsc_vcageind %<>% ff_label("Vaccinations appropriate for age/country?")
data$demographics_complete %<>% ff_label("Complete?")
data$cestdat %<>% ff_label("Onset date of first/earliest symptom")
data$hostdat %<>% ff_label("Admission date at this facility")
data$hosttim %<>% ff_label("Admission time at this facility")
data$readm_cov19 %<>% ff_label("Is the patient being readmitted with Covid-19?")
data$readminreas %<>% ff_label("Please provide reason for readmission: ")
data$readminreasnk %<>% ff_label("Reason for readmission N/K")
data$surgefacil %<>% ff_label("Is this a NIGHTINGALE or other SURGE FACILITY?")
data$hooccur %<>% ff_label("Transfer from other facility?")
data$siteid_transfer %<>% ff_label("If YES: Name of transfer facility:")
data$siteid_transfernk %<>% ff_label("If YES: Name of transfer facility N/K")
data$hostdat_transfer %<>% ff_label("If YES: Admission date at previous facility ")
data$hostdat_transfernk %<>% ff_label("If YES: Admission date at previous facility N/K")
data$subjidcat_transfer %<>% ff_label("If YES - Study Site: Participant ID # at transfer facility")
data$subjid_transfer %<>% ff_label("If DIFFERENT; Participant number Specify CP...e.g Y0401-0001.")
data$travel_erterm %<>% ff_label("Travel in the 14 days prior to first symptom onset?")
data$supper_trcntry %<>% ff_label("If YES, state location: Country")
data$supper_trcity %<>% ff_label("2.6.2 If YES, state location: City/Geographic Area:")
data$erendat %<>% ff_label("If YES, return date:")
data$travel_erterm_2 %<>% ff_label("Travelled to another country in the 14 days...symptom onset?")
data$supper_trcntry_2 %<>% ff_label("If YES, state location: Country")
data$supper_trcity_2 %<>% ff_label("If YES, state location: City/Geographic Area:")
data$erendat_2 %<>% ff_label("If YES, return date:")
data$animal_eryn %<>% ff_label("Contact with animals, raw meat or insect bi...symptom onset?")
data$animal_erterm %<>% ff_label("If YES, specify the animal/insect")
data$animal_erdat %<>% ff_label("If YES, specify the animal/insect date of exposure ")
data$animal_eryn_2 %<>% ff_label("Contact with another animals, raw meat or i...symptom onset?")
data$animal_erterm_2 %<>% ff_label("If YES, specify the animal/insect")
data$animal_erdat_2 %<>% ff_label("If YES, specify the animal/insect date of exposure ")
data$onset_and_admission_complete %<>% ff_label("Complete?")
data$temp_vsyn %<>% ff_label("Temperature on admission available?")
data$temp_vsorres %<>% ff_label("Temperature")
data$temp_vsorresu %<>% ff_label("Temperature Units")
data$hr_vsyn %<>% ff_label("Heart rate on admission available?")
data$hr_vsorres %<>% ff_label("Heart Rate")
data$rr_vsyn %<>% ff_label("Respiratory rate on admission available?")
data$rr_vsorres %<>% ff_label("Respiratory Rate")
data$sysbp_vsyn %<>% ff_label("Systolic blood pressure on admission available? ")
data$sysbp_vsorres %<>% ff_label("Systolic blood pressure")
data$diabp_vsyn %<>% ff_label("Diastolic blood pressure on admission available?")
data$admission_diabp_vsorres %<>% ff_label("Diastolic blood pressure")
data$dehydration_vsorres %<>% ff_label("Severe dehydration: ")
data$stercap_vsyn %<>% ff_label("Sternal capillary refill time  on admission available?")
data$stercap_vsorres %<>% ff_label("Sternal capillary refill time >2 seconds ?")
data$oxy_vsyn %<>% ff_label("Oxygen saturation on admission available: ")
data$oxy_vsorres %<>% ff_label("Oxygen saturation")
data$oxy_vsorresu %<>% ff_label("Oxygen saturation on:")
data$fever_ceoccur_v2 %<>% ff_label("History of fever")
data$cough_ceoccur_v2 %<>% ff_label("Cough")
data$coughsput_ceoccur_v2 %<>% ff_label("Cough: with sputum production")
data$coughhb_ceoccur_v2 %<>% ff_label("Cough: bloody sputum / haemoptysis")
data$sorethroat_ceoccur_v2 %<>% ff_label("Sore throat")
data$runnynose_ceoccur_v2 %<>% ff_label("Runny nose (Rhinorrhoea)")
data$earpain_ceoccur_v2 %<>% ff_label("Ear pain")
data$wheeze_ceoccur_v2 %<>% ff_label("Wheezing")
data$chestpain_ceoccur_v2 %<>% ff_label("Chest pain")
data$myalgia_ceoccur_v2 %<>% ff_label("Muscle aches (Myalgia)")
data$jointpain_ceoccur_v2 %<>% ff_label("Joint pain (Arthralgia)")
data$fatigue_ceoccur_v2 %<>% ff_label("Fatigue / Malaise")
data$shortbreath_ceoccur_v2 %<>% ff_label("Shortness of breath (Dyspnea)")
data$ageusia_ceoccur_v2 %<>% ff_label("Disturbance or loss of taste (Ageusia )")
data$lowerchest_ceoccur_v2 %<>% ff_label("Lower chest wall indrawing")
data$headache_ceoccur_v2 %<>% ff_label("Headache")
data$confusion_ceoccur_v2 %<>% ff_label("Altered consciousness / confusion")
data$seizures_cecoccur_v2 %<>% ff_label("Seizures")
data$abdopain_ceoccur_v2 %<>% ff_label("Abdominal pain")
data$vomit_ceoccur_v2 %<>% ff_label("Vomiting / Nausea")
data$diarrhoea_ceoccur_v2 %<>% ff_label("Diarrhoea")
data$conjunct_ceoccur_v2 %<>% ff_label("Conjunctivitis")
data$rash_ceoccur_v2 %<>% ff_label("Skin rash")
data$skinulcers_ceoccur_v2 %<>% ff_label("Skin ulcers")
data$lymp_ceoccur_v2 %<>% ff_label("Lymphadenopathy")
data$bleed_ceoccur_v2 %<>% ff_label("Bleeding (Haemorrhage)")
data$bleed_ceterm_v2 %<>% ff_label("If Bleeding (others)")
data$anosmia_ceoccur_v2 %<>% ff_label("Disturbance or loss of smell (Anosmia)")
data$bleed_cetermy_v2 %<>% ff_label("If Yes to Bleeding, specify site(s)")
data$admission_signs_and_symptoms_complete %<>% ff_label("Complete?")
data$chrincard %<>% ff_label("Chronic cardiac disease, including congenit...t hypertension)")
data$hypertension_mhyn %<>% ff_label("Hypertension (physician diagnosed)")
data$chronicpul_mhyn %<>% ff_label("Chronic pulmonary disease (not asthma)")
data$asthma_mhyn %<>% ff_label("Asthma (physician diagnosed) ")
data$renal_mhyn %<>% ff_label("Chronic kidney disease")
data$modliv %<>% ff_label("Moderate or severe liver disease")
data$mildliver %<>% ff_label("Mild Liver disease ")
data$chronicneu_mhyn %<>% ff_label("Chronic neurological disorder ")
data$malignantneo_mhyn %<>% ff_label("Malignant neoplasm ")
data$chronichaemo_mhyn %<>% ff_label("Chronic hematologic disease ")
data$aidshiv_mhyn %<>% ff_label("AIDS/HIV ")
data$obesity_mhyn %<>% ff_label("Obesity (as defined by clinical staff)")
data$diabetes_type_mhyn %<>% ff_label("Diabetes and Type")
data$diabetescom_mhyn %<>% ff_label("Diabetes with complications")
data$diabetes_mhyn %<>% ff_label("Diabetes without complications ")
data$rheumatologic_mhyn %<>% ff_label("Rheumatologic disorder ")
data$dementia_mhyn %<>% ff_label("Dementia")
data$malnutrition_mhyn %<>% ff_label("Malnutrition")
data$smoking_mhyn %<>% ff_label("Smoking")
data$other_mhyn %<>% ff_label("Other relevant risk factors?")
data$otherrisktext %<>% ff_label("Other  relevant risk factor; Specify")
data$vulnerable_transplant %<>% ff_label("Solid organ transplant recipients:   ")
data$vulnerable_cancers %<>% ff_label("People with specific cancers: • people wi...pression drugs ")
data$vulnerable_copd %<>% ff_label("People with severe respiratory conditions i...oxygen (COPD):")
data$vulnerable_scid %<>% ff_label("People with rare diseases and inborn errors...ickle cell):   ")
data$vulnerable_immuno %<>% ff_label("People on immunosuppression therapies suffi...of infection: ")
data$vulnerable_preg %<>% ff_label("Women who are pregnant with significant hea...al or acquired:")
data$comorbidities_complete %<>% ff_label("Complete?")
data$immno_cmtrt %<>% ff_label("Treated with immunosuppressants, including...")
data$infect_cmtrt %<>% ff_label("Treated with anti-infectives  for illness e...r to admission?")
data$infect %<>% ff_label("If yes,  please specify anti infectives")
data$chronic_ace_cmoccur %<>% ff_label("Angiotensin converting enzyme inhibitors (ACEI)?")
data$chronic_arb_cmoccur %<>% ff_label("Angiotensin II receptor blockers (ARBs)?")
data$chronic_nsaid_cmoccur %<>% ff_label("Non-steroidal anti-inflammatory (NSAID)?")
data$clinical_frailty %<>% ff_label("Clinical frailty score")
data$preadmission_treatment_complete %<>% ff_label("Complete?")
data$cmtrt %<>% ff_label("Medication name (generic name preferred)  ")
data$cmdose %<>% ff_label("Dose")
data$cmdose_unit %<>% ff_label("Dose unit")
data$cmdose_unitoth %<>% ff_label("Specify other Dose unit")
data$cmdosfrq %<>% ff_label("Dose Frequency")
data$cmdosfrqoth %<>% ff_label("Specify other dose frequency")
data$cmroute %<>% ff_label("Route")
data$cmrouteoth %<>% ff_label("Specify other route")
data$preadmission_medication_complete %<>% ff_label("Complete?")
data$daily_dsstdat %<>% ff_label("DATE OF ASSESSMENT ")
data$daily_hoterm %<>% ff_label("Current admission to ICU/ITU/IMC/HDU")
data$daily_temp_vsorres %<>% ff_label("Highest Temperature")
data$daily_temp_vsorresu %<>% ff_label("Highest Temperature Unit")
data$daily_temp_vsorresnk %<>% ff_label("Highest Temperature N/K")
data$daily_fi02_lbyn %<>% ff_label("FiO2  available / Any supplemental oxygen?")
data$daily_fio2_lborres %<>% ff_label("FiO2 (0.21-1.0)")
data$daily_fio2b_lborres %<>% ff_label("FiO2 %")
data$daily_fio2c_lborres %<>% ff_label("FiO2 L/min (highest)")
data$daily_sa02_lbyn %<>% ff_label("SaO2 (Oxygen saturation in newer CRF) available?")
data$daily_sao2_lborres %<>% ff_label("SaO2 (SpO2 on the newer CRF)")
data$daily_pao2_lbyn %<>% ff_label("PaO2 available?")
data$daily_pao2_lborres %<>% ff_label("PaO2:")
data$daily_pao2_lborresu %<>% ff_label("PaO2 unit:")
data$daily_pao2_lbspec %<>% ff_label("PaO2 sample type")
data$daily_pco2_lbyn %<>% ff_label("PCO2 available?")
data$daily_pco2_lborres %<>% ff_label("PCO2 ")
data$daily_pco2_lborresu %<>% ff_label("PCO2 Unit")
data$daily_ph_lbyn %<>% ff_label("pH available")
data$daily_ph_lborres %<>% ff_label("pH")
data$daily_hco3_lbyn %<>% ff_label("HCO3-  available")
data$daily_hco3_lborres %<>% ff_label("HCO3- ")
data$daily_baseex_lbyn %<>% ff_label("Base excess available")
data$daily_baseex_lborres %<>% ff_label("Base excess")
data$avpu_vsorres %<>% ff_label("AVPU")
data$daily_gcs_lbyn %<>% ff_label("Glasgow Coma Score available?")
data$daily_gcs_vsorres %<>% ff_label("Glasgow Coma Score:")
data$systolic_vsyn %<>% ff_label("Systolic Blood Pressure available?")
data$systolic_vsorres %<>% ff_label("Systolic Pressure")
data$diastolic_vsyn %<>% ff_label("Diastolic Blood Pressure available?")
data$diastolic_vsorres %<>% ff_label("Diastolic Pressure")
data$daily_meanart_lbyn %<>% ff_label("Mean Arterial Pressure available?")
data$daily_meanart_vsorres %<>% ff_label("Mean Arterial Pressure:")
data$daily_urine_lbyn %<>% ff_label("Urine flow rate available?")
data$daily_urine_lborres %<>% ff_label("Urine flow rate:")
data$daily_noninvasive_prtrt %<>% ff_label("Non-invasive ventilation (e.g. NIV (if shor..., BIPAP, CPAP)?")
data$daily_invasive_prtrt %<>% ff_label("Invasive ventilation?")
data$daily_nasaloxy_cmtrt %<>% ff_label("High-flow nasal canula oxygen therapy? (>2L...if shorter CRF)")
data$daily_ecmo_prtrt %<>% ff_label("ECLS/ECMO")
data$daily_rrt_cmtrt %<>% ff_label("Dialysis / Hemofiltration?")
data$daily_inotrope_cmyn %<>% ff_label("Any vasopressor / inotropic support?")
data$daily_dopless5_cmtrt %<>% ff_label("Dopamine <  5 µg/min OR Dobutamine OR Milr...R Levosimendan:")
data$daily_dop5to15_cmtrt %<>% ff_label("Dopamine 5-15 µg/min OR Epinephrine/Norepi...Phenylephrine:")
data$daily_dopgr15_cmtrt %<>% ff_label("Dopamine > 15 µg/min OR Epinephrine/Norepi...0.1 µg/kg/min:")
data$daily_neuro_cmtrt %<>% ff_label("Neuromuscular blocking agents?")
data$daily_nitritc_cmtrt %<>% ff_label("Inhaled Nitric Oxide ?")
data$daily_prone_cmtrt %<>% ff_label("Prone Positioning")
data$daily_trach_prperf %<>% ff_label("Tracheostomy inserted?")
data$daily_prperf %<>% ff_label("Other intervention or procedure?")
data$daily_other_prtrt %<>% ff_label("If YES other intervention, Specify,")
data$daily_lbperf %<>% ff_label("Results available for sample taken on the d...ction 1 above ?")
data$daily_lbdat %<>% ff_label("Date of  assessment")
data$daily_hb_lbyn %<>% ff_label("Haemoglobin available")
data$daily_hbop_lborres %<>% ff_label("Haemoglobin < or > (optional)")
data$daily_hb_lborres %<>% ff_label("Haemoglobin")
data$daily_hb_lborresu %<>% ff_label("Haemoglobin Unit")
data$daily_wbc_lbyn %<>% ff_label("WBC count available")
data$daily_wbcop_lborres %<>% ff_label("WBC count < or > (optional)")
data$daily_wbc_lborres %<>% ff_label("WBC count")
data$daily_wbc_lborresu %<>% ff_label("WBC Unit")
data$daily_lymp_lbyn %<>% ff_label("Lymphocyte count available")
data$daily_lympop_lbyn %<>% ff_label("Lymphocyte count < or > (optional)")
data$daily_lymp_lborres %<>% ff_label("Lymphocyte count")
data$daily_lymp_lborresu %<>% ff_label("Lymphocyte count Unit")
data$daily_neutro_lbyn %<>% ff_label("Neutrophil count available")
data$daily_neutroop_lbyn %<>% ff_label("Neutrophil count < or > (optional)")
data$daily_neutro_lborres %<>% ff_label("Neutrophil count")
data$daily_neutro_lborresu %<>% ff_label("Neutrophil count Unit")
data$daily_haematocrit_lbyn %<>% ff_label("Haematocrit available")
data$daily_haematocrit_lborres %<>% ff_label("Haematocrit")
data$daily_plt_lbyn %<>% ff_label("Platelets available")
data$daily_pltop_lborres %<>% ff_label("Platelet count < or > (optional)")
data$daily_plt_lborres %<>% ff_label("Platelet Count")
data$daily_plt_lborresu %<>% ff_label("Platelets Unit")
data$daily_aptt_lbyn %<>% ff_label("APTT/APTR available")
data$daily_apttop_lborres %<>% ff_label("APTT/APTR < or > (optional)")
data$daily_aptt_lborres %<>% ff_label("APTT/APTR")
data$daily_pt_inr_lbyn %<>% ff_label("PT or INR available")
data$daily_ptop_lborres %<>% ff_label("PT < or > (optional)")
data$daily_pt_lborres %<>% ff_label("PT ")
data$daily_inrop_lborres %<>% ff_label("INR < or > (optional)")
data$daily_inr_lborres %<>% ff_label("INR")
data$daily_alt_lbyn %<>% ff_label("ALT / SGPT available")
data$daily_altop_lbyn %<>% ff_label("ALT / SGPT < or > (optional)")
data$daily_alt_lborres %<>% ff_label("ALT / SGPT")
data$daily_bil_lbyn %<>% ff_label("Total Bilirubin available")
data$daily_bilop_lborres %<>% ff_label("Total Bilirubin < or > (optional)")
data$daily_bil_lborres %<>% ff_label("Total Bilirubin")
data$daily_bil_lborresu %<>% ff_label("Total Bilirubin Unit")
data$daily_ast_lbyn %<>% ff_label("AST/SGOT available")
data$daily_astop_lborres %<>% ff_label("AST/SGOT < or > (optional)")
data$daily_ast_lborres %<>% ff_label("AST/SGOT")
data$daily_glucose_lbyn %<>% ff_label("Glucose available")
data$daily_glucoseop_lborres %<>% ff_label("Glucose < or > (optional)")
data$daily_glucose_lborres %<>% ff_label("Glucose")
data$daily_glucose_lborresu %<>% ff_label("Glucose Unit ")
data$daily_bun_lbyn %<>% ff_label("Blood Urea Nitrogen (urea) available")
data$daily_bunop_lborres %<>% ff_label("Blood Urea Nitrogen (urea) < or > (optional)")
data$daily_bun_lborres %<>% ff_label("Blood Urea Nitrogen (urea)")
data$daily_bun_lborresu %<>% ff_label("Blood Urea Nitrogen (urea) Unit")
data$daily_lactate_lbyn %<>% ff_label("Lactate available")
data$daily_lactateop_lbyn %<>% ff_label("Lactate < or > (optional)")
data$daily_lactate_lborres %<>% ff_label("Lactate")
data$daily_lactate_lborresu %<>% ff_label("Lactate Unit")
data$daily_ldh_lbyn %<>% ff_label("Lactate dehydrogenase (LDH) available?")
data$daily_ldhop_lborres %<>% ff_label("LDH < or > (optional)")
data$daily_ldh_lborres %<>% ff_label("Lactate dehydrogenase (LDH) ")
data$daily_cpk_lby %<>% ff_label("Creatine Phosphokinase (CPK) available?")
data$daily_cpkop_lbyn_2 %<>% ff_label("Creatine Phosphokinase (CPK)  < or > (optional)")
data$daily_cpk_lbyn_2 %<>% ff_label("Creatine Phosphokinase (CPK) ")
data$daily_creat_lbyn %<>% ff_label("Creatinine available")
data$daily_creatop_lborres %<>% ff_label("Creatinine  < or > (optional)")
data$daily_creat_lborres %<>% ff_label("Creatinine")
data$daily_creat_lborresu %<>% ff_label("Creatinine Unit")
data$daily_sodium_lbyn %<>% ff_label("Sodium  available ")
data$daily_sodiumop_lborres %<>% ff_label("Sodium < or > (optional)")
data$daily_sodium_lborres %<>% ff_label("Sodium")
data$daily_sodium_lborresu %<>% ff_label("Sodium Unit")
data$daily_potassium_lbyn %<>% ff_label("Potassium available ")
data$daily_potassiumop_lborres %<>% ff_label("Potassium < or > (optional)")
data$daily_potassium_lborres %<>% ff_label("Potassium")
data$daily_potassium_lborresu %<>% ff_label("Potassium Unit")
data$daily_procal_lbyn %<>% ff_label("Procalcitonin available")
data$daily_procalop_lborres %<>% ff_label("Procalcitonin < or > (optional)")
data$daily_procal_lborres %<>% ff_label("Procalcitonin")
data$daily_crp_lbyn %<>% ff_label("C-reactive protein (CRP) available")
data$daily_crpop_lborres %<>% ff_label("C-reactive protein (CRP) < or > (optional)")
data$daily_crp_lborres %<>% ff_label("C-reactive protein (CRP) For shorter CRF a...to be completed")
data$daily_crp_lborresu %<>% ff_label("C-reactive protein (CRP) Unit")
data$daily_hba1cop_lborres %<>% ff_label("Most recent HbA1c < or > (optional)")
data$daily_hba1c_lborres %<>% ff_label("Most recent HbA1c")
data$daily_hba1c_lborresnk %<>% ff_label("Most recent HbA1c N/K")
data$xray_prperf %<>% ff_label("X-Ray/CT performed (this is chest X-ray if shorter CRF)?")
data$infiltrates_faorres %<>% ff_label("If yes, were infiltrates present?")
data$daily_samples_kitno %<>% ff_label("Where biological samples have been taken fo...IT number here.")
data$daily_form_complete %<>% ff_label("Complete?")
data$arm_participant %<>% ff_label("Arm participant is in")
data$ni_site %<>% ff_label("Northern Ireland? If entering data for Nor...PLEASE SELECT:")
data$inflammatory_mss %<>% ff_label("Adult or child who meets Case Definition fo...system Syndrome")
data$asymptomatic %<>% ff_label("Asymptomatic")
data$no_symptoms %<>% ff_label("None")
data$no_medication %<>% ff_label("No medication currently or within the last 14 days")
data$daily_hco3_lborresu %<>% ff_label("HCO3- Unit")
data$remdesivir %<>% ff_label("Is patient receiving Remdesivir through EAM...criteria?     ")
data$remdesivir_day %<>% ff_label("Which day of Remdesivir therapy is this: (number)         ")
data$remdesivir_last_dose %<>% ff_label("Is this the intended last dose?")
data$daily_haematocrit_lborresu %<>% ff_label("Haematocrit Unit")
data$daily_esr_lbyn %<>% ff_label("ESR available")
data$daily_esrop_lbyn %<>% ff_label("ESR < or > (optional)")
data$daily_esr_lborres %<>% ff_label("ESR")
data$daily_ferr_lbyn %<>% ff_label("Ferritin available")
data$daily_ferrop_lbyn %<>% ff_label("Ferritin < or > (optional)")
data$daily_ferr_lborres %<>% ff_label("Ferritin")
data$daily_ferr_lborresu %<>% ff_label("Ferritin Unit")
data$daily_egfr_lbyn %<>% ff_label("eGFR available")
data$daily_egfrop_lborres %<>% ff_label("eGFR < or > (optional)")
data$daily_egfr_lborres %<>% ff_label("eGFR")
data$daily_egfr_equation___1 %<>% ff_label("eGFR equation/formula (choice=CKD-EPI)")
data$daily_egfr_equation___2 %<>% ff_label("eGFR equation/formula (choice=MDRD)")
data$daily_egfr_equation___3 %<>% ff_label("eGFR equation/formula (choice=CG)")
data$daily_hba1c_lborresu %<>% ff_label("Most recent HbA1c Unit")
data$mbperf %<>% ff_label("Was pathogen testing done during this illness episode?")
data$influ_mbyn %<>% ff_label("Influenza: ")
data$influ_mbcat %<>% ff_label("If Yes to Influenza")
data$influothera_mborres %<>% ff_label("Other influenza A, specify:")
data$influother_mborres %<>% ff_label("Other influenza, specify:")
data$corna_mbcat %<>% ff_label("Coronavirus: ")
data$corna_mbcaty %<>% ff_label("If Yes to Coronavirus:")
data$coronaother_mborres %<>% ff_label("IF Other coronavirus; Specify:")
data$rsv_mbcat %<>% ff_label("RSV")
data$adeno_mbcat %<>% ff_label("Adenovirus")
data$bact_mborres %<>% ff_label("Bacteria")
data$bacteria_mborres %<>% ff_label("If yes, specify bacteria (list all below)")
data$other_mbyn %<>% ff_label("Other Infectious Respiratory Diagnosis: ")
data$other_mborres %<>% ff_label(" If YES: Other infectious respiratory diagnosis, specify:")
data$clinicalpneu_mborres %<>% ff_label("Clinical pneumonia: ")
data$infectuk_mborres %<>% ff_label("IF NONE OF THE ABOVE: Suspected Non-infective:")
data$infectious_respiratory_disease_pathogen_diagnosis_complete %<>% ff_label("Complete?")
data$daily_mbperf %<>% ff_label("Pathogen testing done")
data$llimsno_bnum %<>% ff_label("LIMS number")
data$mbdat %<>% ff_label("Collection Date")
data$mbspec %<>% ff_label("Bio specimen type")
data$other_mbspec %<>% ff_label("If  OTHER; Specify")
data$mbmethod %<>% ff_label("Laboratory Test Method")
data$other_mbmethod %<>% ff_label("If Other Laboratory test method; Specify")
data$mborres %<>% ff_label("Result")
data$mbtestcd %<>% ff_label("Pathogen Tested / Detected")
data$infectious_respiratory_disease_pathogen_testing_complete %<>% ff_label("Complete?")
data$antiviral_cmyn %<>% ff_label("Antiviral agent?")
data$antiviral_cmtrt___1 %<>% ff_label("IF YES to antiviral agent (choice=Ribavirin)")
data$antiviral_cmtrt___2 %<>% ff_label("IF YES to antiviral agent (choice=Lopinavir/Ritonvir)")
data$antiviral_cmtrt___3 %<>% ff_label("IF YES to antiviral agent (choice=Interferon alpha)")
data$antiviral_cmtrt___4 %<>% ff_label("IF YES to antiviral agent (choice=Interferon beta)")
data$antiviral_cmtrt___7 %<>% ff_label("IF YES to antiviral agent (choice=Chloroquine /...hloroquine)")
data$antiviral_cmtrt___8 %<>% ff_label("IF YES to antiviral agent (choice=Remdesivir)")
data$antiviral_cmtrt___9 %<>% ff_label("IF YES to antiviral agent (choice=IL6 inhibitor)")
data$antiviral_cmtrt___5 %<>% ff_label("IF YES to antiviral agent (choice=Neuraminidase inhibitors)")
data$antiviral_cmtrt___6 %<>% ff_label("IF YES to antiviral agent (choice=Other)")
data$remdes_cmtrt_first %<>% ff_label("If  YES to Remdesivir: first dose")
data$remdes_cmtrt_last %<>% ff_label("If  YES to Remdesivir: last dose")
data$il6_cmtrt %<>% ff_label("If  YES to IL6 inhibitor: which")
data$il6_cmtrt_other %<>% ff_label("Specify other IL6 inhibitor:")
data$il6_cmtrt_first %<>% ff_label("If  YES to  IL6 inhibitor: first dose")
data$il6_cmtrt_last %<>% ff_label("If  YES to IL6 inhibitor: last dose")
data$neuro_cmtrt %<>% ff_label("If  Neuraminidase inhibitors; Specify which")
data$othantiviral_cmtrt %<>% ff_label("If  Other antiviral agent; Specify type")
data$othantiviral2_cmyn %<>% ff_label("Would you like to add another antiviral?")
data$othhantiviral2_cmtrt %<>% ff_label("If  Other antiviral agent; Specify type")
data$othantiviral3_cmyn %<>% ff_label("Would you like to add another antiviral?")
data$othantiviral3_cmtrt %<>% ff_label("If  Other antiviral agent; Specify type")
data$othantiviral4_cmyn %<>% ff_label("Would you like to add another antiviral?")
data$othantiviral4_cmtrt %<>% ff_label("If  Other antiviral agent; Specify type")
data$othantiviral5_cmyn %<>% ff_label("Would you like to add another antiviral?")
data$othantiviral5_cmtrt %<>% ff_label("If  Other antiviral agent; Specify type")
data$antibiotic_cmyn %<>% ff_label("Antibiotic agent?")
data$antibiotic_cmtrt %<>% ff_label("IF YES to antibiotic agent; Specify type")
data$antibiotic2_cmyn %<>% ff_label("Would you like to add another antibiotic?")
data$antibiotic2_cmtrt %<>% ff_label("IF YES to antibiotic agent; Specify type")
data$antibiotic3_cmyn %<>% ff_label("Would you like to add another antibiotic?")
data$antibiotic3_cmtrt %<>% ff_label("IF YES to antibiotic agent; Specify type")
data$antibiotic4_cmyn %<>% ff_label("Would you like to add another antibiotic?")
data$antibiotic4_cmtrt %<>% ff_label("IF YES to antibiotic agent; Specify type")
data$antibiotic5_cmyn %<>% ff_label("Would you like to add another antibiotic?")
data$antibiotic5_cmtrt %<>% ff_label("IF YES to antibiotic agent; Specify type")
data$antibiotic6_cmyn %<>% ff_label("Would you like to add another antibiotic?")
data$antibiotic6_cmtrt %<>% ff_label("IF YES to antibiotic agent; Specify type")
data$antibiotic7_cmyn %<>% ff_label("Would you like to add another antibiotic?")
data$antibiotic7_cmtrt %<>% ff_label("IF YES to antibiotic agent; Specify type")
data$corticost_cmyn %<>% ff_label("Corticosteroid agent?")
data$corticost_cmroute %<>% ff_label("If YES to Corticosteroid, specify Route")
data$corticost_cmtrt %<>% ff_label("If YES to Corticosteroid, specify type")
data$corticost_cmdose %<>% ff_label("If YES to Corticosteroid, specify dose")
data$corticost2_cmyn %<>% ff_label("Would you like to add another Corticosteroid agent?")
data$corticost2_cmroute %<>% ff_label("If YES to Corticosteroid, specify Route")
data$corticost2_cmtrt %<>% ff_label("If YES to Corticosteroid, specify type")
data$corticost2_cmdose %<>% ff_label("If YES to Corticosteroid, specify dose")
data$corticost3_cmyn %<>% ff_label("Would you like to add another Corticosteroid agent?")
data$corticost3_cmroute %<>% ff_label("If YES to Corticosteroid, specify Route")
data$corticost3_cmtrt %<>% ff_label("If YES to Corticosteroid, specify type")
data$corticost3_cmdose %<>% ff_label("If YES to Corticosteroid, specify dose")
data$dexamethasone %<>% ff_label("Dexamethasone 6mg once per day?")
data$dexamethasone_route %<>% ff_label("If Yes to Dexamethasone, specify Route:")
data$antifung_cmyn %<>% ff_label("Antifungal agent?")
data$antifungal_cmtrt %<>% ff_label("IF YES to antifungal agent; Specify which")
data$offlabel_cmyn %<>% ff_label("Off-label / Compassionate Use medications?  ")
data$offlabel_cmtrt %<>% ff_label("IF YES to Off-label / Compassionate Use med...; Specify which")
data$interleukin_cmyn %<>% ff_label("Interleukin inhibitors    ")
data$interleukin_cmtrt %<>% ff_label("IF YES to Interleukin inhibitors; Specify which   ")
data$conv_plasma_cmyn %<>% ff_label("Convalescent plasma     ")
data$icu_hoterm %<>% ff_label("ICU or High Dependency admission")
data$hodur %<>% ff_label("If YES, total duration (days)")
data$icu_hostdat %<>% ff_label("Date of ICU/HDU admission:")
data$icu_hoendat %<>% ff_label("Date of ICU/HDU discharge:")
data$oxygen_cmoccur %<>% ff_label("Oxygen therapy")
data$oxygenhf_cmoccur %<>% ff_label("High Flow Oxygen therapy?  (>2l/min )")
data$noninvasive_proccur %<>% ff_label("Non-invasive ventilation ? (e.g. BIPAP, CPAP)")
data$invasive_proccur %<>% ff_label("Invasive ventilation (Any intubation) ?")
data$pronevent_prtrt %<>% ff_label("Prone ventilation")
data$inhalednit_cmtrt %<>% ff_label("Inhaled Nitric Oxide")
data$tracheo_prtrt %<>% ff_label("Tracheostomy inserted")
data$extracorp_prtrt %<>% ff_label("Extracorporeal (ECMO) support")
data$rrt_prtrt %<>% ff_label("Renal replacement therapy (RRT) or dialysis")
data$inotrop_cmtrt %<>% ff_label("Inotropes / vasopressors")
data$invasive_prdur %<>% ff_label("If yes to Invasive ventilation; confirm duration ")
data$excorp_prdur %<>% ff_label("If YES to Extracorporeal (ECMO) support; confirm duration")
data$inotrope_cmdur %<>% ff_label("If YES to Inotropes/vasopressors; confirm duration")
data$other_cmyn %<>% ff_label("OTHER intervention or procedure")
data$other_cm %<>% ff_label("IF  YES OTHER intervention or procedure; Specify")
data$bloodgroup %<>% ff_label("Blood Group (please check past as well as c...medical record)")
data$treatment_complete %<>% ff_label("Complete?")
data$vrialpneu_ceoccur %<>% ff_label("Viral Pneumonia")
data$bactpneu_ceoccur %<>% ff_label("Bacterial pneumonia")
data$ards_ceoccur %<>% ff_label("Acute Respiratory Syndrome")
data$cryptogenic_ceterm %<>% ff_label("Cryptogenic organizing pneumonia (COP)")
data$pneumothorax_ceterm %<>% ff_label("Pneumothorax")
data$pleuraleff_ceterm %<>% ff_label("Pleural effusion")
data$bronchio_ceterm %<>% ff_label("Bronchiolitis")
data$meningitis_ceterm %<>% ff_label("Meningitis / Encephalitis")
data$seizure_ceterm %<>% ff_label("Seizure")
data$stroke_ceterm %<>% ff_label("Stroke / Cerebrovascular accident")
data$neuro_comp %<>% ff_label("Other neurological complication")
data$heartfailure_ceterm %<>% ff_label("Congestive heart failure")
data$endocarditis_aeterm %<>% ff_label("Endocarditis / Myocarditis Pericarditis (fo...ocarditis only)")
data$myocarditis_ceterm %<>% ff_label("Myocarditis / Pericarditis")
data$cardiomyopathy_ceterm %<>% ff_label("Cardiomyopathy")
data$arrhythmia_ceterm %<>% ff_label("Cardiac arrhythmia")
data$ischaemia_ceterm %<>% ff_label("Cardiac ischemia")
data$cardiacarrest_ceterm %<>% ff_label("Cardiac arrest")
data$bacteraemia_ceterm %<>% ff_label("Bacteraemia")
data$coagulo_ceterm %<>% ff_label("Coagulation disorder / Disseminated intrava...lar coagulation")
data$aneamia_ceterm %<>% ff_label("Anaemia")
data$rhabdomyolsis_ceterm %<>% ff_label("Rhabdomyolysis / Myositis")
data$renalinjury_ceterm %<>% ff_label("Acute renal injury / Acute renal failure")
data$gastro_ceterm %<>% ff_label("Gastrointestinal hemorrhage")
data$pancreat_ceterm %<>% ff_label("Pancreatitis")
data$liverdysfunction_ceterm %<>% ff_label("Liver dysfunction")
data$hyperglycemia_aeterm %<>% ff_label("Hyperglycaemia")
data$hypoglycemia_ceterm %<>% ff_label("Hypoglycaemia")
data$other_ceoccur %<>% ff_label("Other")
data$other_ceterm %<>% ff_label("If  Other; Specify")
data$complications_complete %<>% ff_label("Complete?")
data$recruitment %<>% ff_label("Is/Has the participant being recruited to a...and hospital)?")
data$study_1_name %<>% ff_label("If YES, specify name of study:   ")
data$study_1_id %<>% ff_label("Study Participant ID:   ")
data$study_2 %<>% ff_label("Add another study?")
data$study_2_name %<>% ff_label("If YES, specify name of study: ")
data$study_2_id %<>% ff_label("Study Participant ID: ")
data$study_3 %<>% ff_label("Add another study? ")
data$study_3_name %<>% ff_label("If YES, specify name of study: ")
data$study_3_id %<>% ff_label("Study Participant ID: ")
data$study_participation_complete %<>% ff_label("Complete?")
data$dsterm %<>% ff_label("Outcome:")
data$dshosp %<>% ff_label("If hospitalised:")
data$dsstdtcyn %<>% ff_label("Is the Outcome date known")
data$dsstdtc %<>% ff_label("Outcome date")
data$suppds_qval %<>% ff_label("If Discharged alive: Ability to self-care a...before illness")
data$oxygen_proccur %<>% ff_label("Oxygen therapy")
data$renal_proccur %<>% ff_label("Dialysis / renal treatment?")
data$other_cmoccur %<>% ff_label("Other intervention or procedure?")
data$other_cmtrt %<>% ff_label("If YES: Specify (multiple permitted)")
data$siteid %<>% ff_label("If Transferred: Facility name")
data$siteidnk %<>% ff_label("If Transferred: Facility name N/K")
data$siteyn %<>% ff_label("If Transferred: Is the transfer facility a study site?")
data$subjidcat %<>% ff_label("If a Study Site: Participant number at new facility")
data$transfer_subjid %<>% ff_label("If Different, Participant number at the new....g Y0401-0001).")
data$outcome_complete %<>% ff_label("Complete?")
data$core_addinfo %<>% ff_label("Additional Information")
data$core_additional_information_complete %<>% ff_label("Complete?")
data$withddat %<>% ff_label("Date of withdrawal:")
data$withdtype %<>% ff_label("Type of withdrawal:")
data$withdreas %<>% ff_label("Reason for withdrawal:")
data$withdrawal_form_complete %<>% ff_label("Complete?")
data$consent_given %<>% ff_label("Any mode of Consent or Assent Given : ")
data$consent_daterec %<>% ff_label("Date received:")
data$consent_mode___1 %<>% ff_label("Mode of consent (check all that apply):  (choice=Adult)")
data$consent_mode___2 %<>% ff_label("Mode of consent (check all that apply):  (choice=Adult Extra C...t Sampling)")
data$consent_mode___3 %<>% ff_label("Mode of consent (check all that apply):  (choice=Adult BioAID)")
data$consent_mode___4 %<>% ff_label("Mode of consent (check all that apply):  (choice=Consultee)")
data$consent_mode___5 %<>% ff_label("Mode of consent (check all that apply):  (choice=Witnessed)")
data$consent_mode___6 %<>% ff_label("Mode of consent (check all that apply):  (choice=Telephone)")
data$consent_mode___7 %<>% ff_label("Mode of consent (check all that apply):  (choice=Next of Kin (...land only))")
data$consent_mode___8 %<>% ff_label("Mode of consent (check all that apply):  (choice=Adult Regaine...land only))")
data$consent_mode___9 %<>% ff_label("Mode of consent (check all that apply):  (choice=Young Person 12-18y)")
data$consent_mode___10 %<>% ff_label("Mode of consent (check all that apply):  (choice=Child under 12y)")
data$consent_mode___11 %<>% ff_label("Mode of consent (check all that apply):  (choice=Parent/Guardian)")
data$consent_optcondit___1 %<>% ff_label("Agreement to optional conditions of consent...l that apply):  (choice=Other unrelated use)")
data$consent_optcondit___2 %<>% ff_label("Agreement to optional conditions of consent...l that apply):  (choice=Manufacture a...rcial lack)")
data$consent_optcondit___3 %<>% ff_label("Agreement to optional conditions of consent...l that apply):  (choice=DNA RNA sequence sharing)")
data$consent_optcondit___4 %<>% ff_label("Agreement to optional conditions of consent...l that apply):  (choice=Future contac...sage (SMS))")
data$consent_phone %<>% ff_label("If yes to future contact by mobile phone, e...phone number: ")
data$consent_ctu_dms_complete %<>% ff_label("Complete?")